/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) func_aerobat_aero_R_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_to_mex CASADI_PREFIX(to_mex)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s6[40] = {3, 14, 0, 1, 2, 3, 6, 9, 11, 11, 11, 11, 11, 14, 17, 20, 23, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s7[29] = {14, 3, 0, 8, 16, 23, 0, 3, 4, 5, 10, 11, 12, 13, 1, 3, 4, 5, 10, 11, 12, 13, 2, 3, 4, 10, 11, 12, 13};
static const casadi_int casadi_s8[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s9[35] = {31, 1, 0, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., -1., 0., 0., 0., 1.};
static const casadi_real casadi_c3[3] = {1., 0., 0.};

/* f:(i0[14],i1[14],i2[31],i3[3])->(o0[14x3,23nz],o1[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, w2, w3, *w4=w+29, *w5=w+38, w6, w7, w8, w9, *w10=w+51, *w11=w+54, *w12=w+57, *w13=w+60, *w14=w+69, w15, *w16=w+79, *w17=w+88, *w18=w+97, *w19=w+106, *w20=w+115, *w21=w+124, *w22=w+133, w23, w24, *w25=w+144, *w26=w+147, w27, *w28=w+157, *w29=w+166, *w30=w+175, w31, w32, *w33=w+186, *w34=w+195, *w35=w+204, *w36=w+213, w37, w38, w39, *w40=w+219, w41, w42, w43, w44, w45, w46, *w47=w+228, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, *w63=w+252, *w64=w+261, w65, w66, *w67=w+272, *w68=w+295;
  /* #0: @0 = zeros(14x3,23nz) */
  casadi_clear(w0, 23);
  /* #1: @1 = ones(3x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: (@0[0] = @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #4: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #5: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #6: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #7: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #8: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #9: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #10: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #11: @8 = (-@8) */
  w8 = (- w8 );
  /* #12: @9 = 0 */
  w9 = 0.;
  /* #13: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #14: @10 = @10' */
  /* #15: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #16: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #19: @11 = @11' */
  /* #20: @12 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w12);
  /* #21: @12 = @12' */
  /* #22: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #23: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #24: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #25: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #26: @9 = 0 */
  w9 = 0.;
  /* #27: @15 = sin(@7) */
  w15 = sin( w7 );
  /* #28: @10 = horzcat(@8, @9, @15) */
  rr=w10;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #29: @10 = @10' */
  /* #30: @11 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w11);
  /* #31: @11 = @11' */
  /* #32: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #33: @8 = (-@8) */
  w8 = (- w8 );
  /* #34: @9 = 0 */
  w9 = 0.;
  /* #35: @15 = cos(@7) */
  w15 = cos( w7 );
  /* #36: @12 = horzcat(@8, @9, @15) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #37: @12 = @12' */
  /* #38: @16 = horzcat(@10, @11, @12) */
  rr=w16;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #39: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #40: @5 = mac(@14,@17,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #41: @14 = @5' */
  for (i=0, rr=w14, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #42: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #43: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #44: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #45: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #46: @10 = input[3][0] */
  casadi_copy(arg[3], 3, w10);
  /* #47: @11 = @10' */
  casadi_copy(w10, 3, w11);
  /* #48: @20 = mac(@1,@11,@20) */
  casadi_mtimes((&w1), casadi_s2, w11, casadi_s1, w20, casadi_s0, w, 0);
  /* #49: @21 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w21);
  /* #50: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #51: @19 = mac(@20,@22,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #52: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #53: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w11);
  /* #54: @11 = @11' */
  /* #55: @8 = 0 */
  w8 = 0.;
  /* #56: @9 = input[0][12] */
  w9 = arg[0] ? arg[0][12] : 0;
  /* #57: @15 = cos(@9) */
  w15 = cos( w9 );
  /* #58: @23 = (-@9) */
  w23 = (- w9 );
  /* #59: @24 = sin(@23) */
  w24 = sin( w23 );
  /* #60: @24 = (-@24) */
  w24 = (- w24 );
  /* #61: @12 = horzcat(@8, @15, @24) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w24;
  /* #62: @12 = @12' */
  /* #63: @8 = 0 */
  w8 = 0.;
  /* #64: @23 = sin(@23) */
  w23 = sin( w23 );
  /* #65: @15 = cos(@9) */
  w15 = cos( w9 );
  /* #66: @25 = horzcat(@8, @23, @15) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w23;
  *rr++ = w15;
  /* #67: @25 = @25' */
  /* #68: @22 = horzcat(@11, @12, @25) */
  rr=w22;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #69: @26 = @22' */
  for (i=0, rr=w26, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #70: @8 = input[0][13] */
  w8 = arg[0] ? arg[0][13] : 0;
  /* #71: @23 = cos(@8) */
  w23 = cos( w8 );
  /* #72: @15 = 0 */
  w15 = 0.;
  /* #73: @24 = (-@8) */
  w24 = (- w8 );
  /* #74: @27 = sin(@24) */
  w27 = sin( w24 );
  /* #75: @11 = horzcat(@23, @15, @27) */
  rr=w11;
  *rr++ = w23;
  *rr++ = w15;
  *rr++ = w27;
  /* #76: @11 = @11' */
  /* #77: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #78: @12 = @12' */
  /* #79: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #80: @24 = (-@24) */
  w24 = (- w24 );
  /* #81: @23 = 0 */
  w23 = 0.;
  /* #82: @15 = cos(@8) */
  w15 = cos( w8 );
  /* #83: @25 = horzcat(@24, @23, @15) */
  rr=w25;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w15;
  /* #84: @25 = @25' */
  /* #85: @28 = horzcat(@11, @12, @25) */
  rr=w28;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #86: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #87: @20 = mac(@26,@29,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #88: @26 = @20' */
  for (i=0, rr=w26, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #89: @18 = mac(@19,@26,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #90: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #91: @24 = input[0][11] */
  w24 = arg[0] ? arg[0][11] : 0;
  /* #92: @23 = cos(@24) */
  w23 = cos( w24 );
  /* #93: @15 = sin(@24) */
  w15 = sin( w24 );
  /* #94: @15 = (-@15) */
  w15 = (- w15 );
  /* #95: @27 = 0 */
  w27 = 0.;
  /* #96: @11 = horzcat(@23, @15, @27) */
  rr=w11;
  *rr++ = w23;
  *rr++ = w15;
  *rr++ = w27;
  /* #97: @11 = @11' */
  /* #98: @23 = sin(@24) */
  w23 = sin( w24 );
  /* #99: @15 = cos(@24) */
  w15 = cos( w24 );
  /* #100: @27 = 0 */
  w27 = 0.;
  /* #101: @12 = horzcat(@23, @15, @27) */
  rr=w12;
  *rr++ = w23;
  *rr++ = w15;
  *rr++ = w27;
  /* #102: @12 = @12' */
  /* #103: @25 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w25);
  /* #104: @25 = @25' */
  /* #105: @29 = horzcat(@11, @12, @25) */
  rr=w29;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #106: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #107: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w11);
  /* #108: @11 = @11' */
  /* #109: @23 = 0 */
  w23 = 0.;
  /* #110: @15 = input[0][10] */
  w15 = arg[0] ? arg[0][10] : 0;
  /* #111: @27 = cos(@15) */
  w27 = cos( w15 );
  /* #112: @31 = (-@15) */
  w31 = (- w15 );
  /* #113: @32 = sin(@31) */
  w32 = sin( w31 );
  /* #114: @32 = (-@32) */
  w32 = (- w32 );
  /* #115: @12 = horzcat(@23, @27, @32) */
  rr=w12;
  *rr++ = w23;
  *rr++ = w27;
  *rr++ = w32;
  /* #116: @12 = @12' */
  /* #117: @23 = 0 */
  w23 = 0.;
  /* #118: @31 = sin(@31) */
  w31 = sin( w31 );
  /* #119: @27 = cos(@15) */
  w27 = cos( w15 );
  /* #120: @25 = horzcat(@23, @31, @27) */
  rr=w25;
  *rr++ = w23;
  *rr++ = w31;
  *rr++ = w27;
  /* #121: @25 = @25' */
  /* #122: @33 = horzcat(@11, @12, @25) */
  rr=w33;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #123: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #124: @26 = mac(@30,@34,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w30+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #125: @30 = @26' */
  for (i=0, rr=w30, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #126: @17 = mac(@18,@30,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #127: @30 = zeros(3x3) */
  casadi_clear(w30, 9);
  /* #128: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #129: @34 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w34);
  /* #130: @12 = input[2][7] */
  casadi_copy(arg[2] ? arg[2]+13 : 0, 3, w12);
  /* #131: @11 = mac(@34,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #132: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #133: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #134: @35 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w35);
  /* #135: @34 = mac(@26,@35,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #136: @25 = input[2][8] */
  casadi_copy(arg[2] ? arg[2]+16 : 0, 3, w25);
  /* #137: @12 = mac(@34,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w25+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #138: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #139: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #140: @30 = mac(@1,@12,@30) */
  casadi_mtimes((&w1), casadi_s2, w12, casadi_s1, w30, casadi_s0, w, 0);
  /* #141: @17 = (@17+@30) */
  for (i=0, rr=w17, cs=w30; i<9; ++i) (*rr++) += (*cs++);
  /* #142: @4 = mac(@14,@17,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #143: @14 = @4' */
  for (i=0, rr=w14, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #144: {NULL, @12, @36} = horzsplit(@14) */
  casadi_copy(w14+3, 3, w12);
  casadi_copy(w14+6, 3, w36);
  /* #145: @36 = @36' */
  /* #146: {NULL, @23, @31} = horzsplit(@36) */
  w23 = w36[1];
  w31 = w36[2];
  /* #147: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #148: @27 = sin(@2) */
  w27 = sin( w2 );
  /* #149: @31 = (@27*@31) */
  w31  = (w27*w31);
  /* #150: @23 = (@23-@31) */
  w23 -= w31;
  /* #151: @31 = cos(@2) */
  w31 = cos( w2 );
  /* #152: @12 = @12' */
  /* #153: {NULL, @32, @37} = horzsplit(@12) */
  w32 = w12[1];
  w37 = w12[2];
  /* #154: @37 = (@31*@37) */
  w37  = (w31*w37);
  /* #155: @23 = (@23-@37) */
  w23 -= w37;
  /* #156: @37 = sin(@2) */
  w37 = sin( w2 );
  /* #157: @32 = (@37*@32) */
  w32  = (w37*w32);
  /* #158: @23 = (@23-@32) */
  w23 -= w32;
  /* #159: (@0[1] = @23) */
  for (rr=w0+1, ss=(&w23); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #160: @23 = cos(@7) */
  w23 = cos( w7 );
  /* #161: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #162: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #163: @12 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w12);
  /* #164: @12 = @12' */
  /* #165: @32 = 0 */
  w32 = 0.;
  /* #166: @38 = cos(@2) */
  w38 = cos( w2 );
  /* #167: @39 = sin(@2) */
  w39 = sin( w2 );
  /* #168: @39 = (-@39) */
  w39 = (- w39 );
  /* #169: @36 = horzcat(@32, @38, @39) */
  rr=w36;
  *rr++ = w32;
  *rr++ = w38;
  *rr++ = w39;
  /* #170: @36 = @36' */
  /* #171: @32 = 0 */
  w32 = 0.;
  /* #172: @38 = sin(@2) */
  w38 = sin( w2 );
  /* #173: @39 = cos(@2) */
  w39 = cos( w2 );
  /* #174: @40 = horzcat(@32, @38, @39) */
  rr=w40;
  *rr++ = w32;
  *rr++ = w38;
  *rr++ = w39;
  /* #175: @40 = @40' */
  /* #176: @30 = horzcat(@12, @36, @40) */
  rr=w30;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  /* #177: @4 = mac(@17,@30,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #178: @14 = mac(@13,@4,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #179: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #180: {@12, NULL, @36} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+6, 3, w36);
  /* #181: @36 = @36' */
  /* #182: {@32, NULL, @38} = horzsplit(@36) */
  w32 = w36[0];
  w38 = w36[2];
  /* #183: @32 = (@23*@32) */
  w32  = (w23*w32);
  /* #184: @32 = (-@32) */
  w32 = (- w32 );
  /* #185: @39 = sin(@7) */
  w39 = sin( w7 );
  /* #186: @38 = (@39*@38) */
  w38  = (w39*w38);
  /* #187: @32 = (@32-@38) */
  w32 -= w38;
  /* #188: @38 = cos(@7) */
  w38 = cos( w7 );
  /* #189: @12 = @12' */
  /* #190: {@41, NULL, @42} = horzsplit(@12) */
  w41 = w12[0];
  w42 = w12[2];
  /* #191: @42 = (@38*@42) */
  w42  = (w38*w42);
  /* #192: @32 = (@32+@42) */
  w32 += w42;
  /* #193: @42 = sin(@7) */
  w42 = sin( w7 );
  /* #194: @41 = (@42*@41) */
  w41  = (w42*w41);
  /* #195: @32 = (@32-@41) */
  w32 -= w41;
  /* #196: (@0[2] = @32) */
  for (rr=w0+2, ss=(&w32); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #197: @32 = cos(@6) */
  w32 = cos( w6 );
  /* #198: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #199: @17 = mac(@4,@16,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #200: @4 = @17' */
  for (i=0, rr=w4, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #201: {@12, @36, NULL} = horzsplit(@4) */
  casadi_copy(w4, 3, w12);
  casadi_copy(w4+3, 3, w36);
  /* #202: @36 = @36' */
  /* #203: {@41, @43, NULL} = horzsplit(@36) */
  w41 = w36[0];
  w43 = w36[1];
  /* #204: @41 = (@32*@41) */
  w41  = (w32*w41);
  /* #205: @44 = sin(@6) */
  w44 = sin( w6 );
  /* #206: @43 = (@44*@43) */
  w43  = (w44*w43);
  /* #207: @41 = (@41-@43) */
  w41 -= w43;
  /* #208: @43 = cos(@6) */
  w43 = cos( w6 );
  /* #209: @12 = @12' */
  /* #210: {@45, @46, NULL} = horzsplit(@12) */
  w45 = w12[0];
  w46 = w12[1];
  /* #211: @46 = (@43*@46) */
  w46  = (w43*w46);
  /* #212: @41 = (@41-@46) */
  w41 -= w46;
  /* #213: @46 = sin(@6) */
  w46 = sin( w6 );
  /* #214: @45 = (@46*@45) */
  w45  = (w46*w45);
  /* #215: @41 = (@41-@45) */
  w41 -= w45;
  /* #216: (@0[3] = @41) */
  for (rr=w0+3, ss=(&w41); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #217: @41 = cos(@15) */
  w41 = cos( w15 );
  /* #218: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #219: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #220: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #221: @34 = @30' */
  for (i=0, rr=w34, cs=w30; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #222: @14 = mac(@5,@34,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #223: @34 = @14' */
  for (i=0, rr=w34, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #224: @17 = mac(@34,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #225: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #226: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #227: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #228: @47 = @14' */
  for (i=0, rr=w47, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #229: @12 = mac(@47,@1,@12) */
  casadi_mtimes(w47, casadi_s0, (&w1), casadi_s2, w12, casadi_s3, w, 0);
  /* #230: @36 = @25' */
  casadi_copy(w25, 3, w36);
  /* #231: @18 = mac(@12,@36,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w36+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #232: @47 = @35' */
  for (i=0, rr=w47, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #233: @34 = mac(@18,@47,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #234: @17 = (@17+@34) */
  for (i=0, rr=w17, cs=w34; i<9; ++i) (*rr++) += (*cs++);
  /* #235: @4 = mac(@29,@17,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #236: @34 = @4' */
  for (i=0, rr=w34, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #237: {NULL, @12, @36} = horzsplit(@34) */
  casadi_copy(w34+3, 3, w12);
  casadi_copy(w34+6, 3, w36);
  /* #238: @36 = @36' */
  /* #239: {NULL, @1, @45} = horzsplit(@36) */
  w1 = w36[1];
  w45 = w36[2];
  /* #240: @1 = (@41*@1) */
  w1  = (w41*w1);
  /* #241: @48 = cos(@15) */
  w48 = cos( w15 );
  /* #242: @12 = @12' */
  /* #243: {NULL, @49, @50} = horzsplit(@12) */
  w49 = w12[1];
  w50 = w12[2];
  /* #244: @50 = (@48*@50) */
  w50  = (w48*w50);
  /* #245: @1 = (@1-@50) */
  w1 -= w50;
  /* #246: @1 = (-@1) */
  w1 = (- w1 );
  /* #247: @50 = sin(@15) */
  w50 = sin( w15 );
  /* #248: @45 = (@50*@45) */
  w45  = (w50*w45);
  /* #249: @1 = (@1-@45) */
  w1 -= w45;
  /* #250: @45 = sin(@15) */
  w45 = sin( w15 );
  /* #251: @49 = (@45*@49) */
  w49  = (w45*w49);
  /* #252: @1 = (@1-@49) */
  w1 -= w49;
  /* #253: (@0[4] = @1) */
  for (rr=w0+4, ss=(&w1); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #254: @1 = cos(@24) */
  w1 = cos( w24 );
  /* #255: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #256: @34 = mac(@17,@33,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #257: @17 = @34' */
  for (i=0, rr=w17, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #258: {@12, @36, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+3, 3, w36);
  /* #259: @36 = @36' */
  /* #260: {@49, @51, NULL} = horzsplit(@36) */
  w49 = w36[0];
  w51 = w36[1];
  /* #261: @49 = (@1*@49) */
  w49  = (w1*w49);
  /* #262: @52 = sin(@24) */
  w52 = sin( w24 );
  /* #263: @51 = (@52*@51) */
  w51  = (w52*w51);
  /* #264: @49 = (@49-@51) */
  w49 -= w51;
  /* #265: @51 = cos(@24) */
  w51 = cos( w24 );
  /* #266: @12 = @12' */
  /* #267: {@53, @54, NULL} = horzsplit(@12) */
  w53 = w12[0];
  w54 = w12[1];
  /* #268: @54 = (@51*@54) */
  w54  = (w51*w54);
  /* #269: @49 = (@49-@54) */
  w49 -= w54;
  /* #270: @54 = sin(@24) */
  w54 = sin( w24 );
  /* #271: @53 = (@54*@53) */
  w53  = (w54*w53);
  /* #272: @49 = (@49-@53) */
  w49 -= w53;
  /* #273: (@0[5] = @49) */
  for (rr=w0+5, ss=(&w49); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #274: @49 = cos(@9) */
  w49 = cos( w9 );
  /* #275: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #276: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #277: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #278: @4 = mac(@14,@26,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #279: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #280: @34 = mac(@18,@19,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #281: @17 = mac(@34,@28,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #282: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #283: {NULL, @12, @36} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w36);
  /* #284: @36 = @36' */
  /* #285: {NULL, @53, @55} = horzsplit(@36) */
  w53 = w36[1];
  w55 = w36[2];
  /* #286: @53 = (@49*@53) */
  w53  = (w49*w53);
  /* #287: @56 = cos(@9) */
  w56 = cos( w9 );
  /* #288: @12 = @12' */
  /* #289: {NULL, @57, @58} = horzsplit(@12) */
  w57 = w12[1];
  w58 = w12[2];
  /* #290: @58 = (@56*@58) */
  w58  = (w56*w58);
  /* #291: @53 = (@53-@58) */
  w53 -= w58;
  /* #292: @53 = (-@53) */
  w53 = (- w53 );
  /* #293: @58 = sin(@9) */
  w58 = sin( w9 );
  /* #294: @55 = (@58*@55) */
  w55  = (w58*w55);
  /* #295: @53 = (@53-@55) */
  w53 -= w55;
  /* #296: @55 = sin(@9) */
  w55 = sin( w9 );
  /* #297: @57 = (@55*@57) */
  w57  = (w55*w57);
  /* #298: @53 = (@53-@57) */
  w53 -= w57;
  /* #299: (@0[6] = @53) */
  for (rr=w0+6, ss=(&w53); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #300: @53 = cos(@8) */
  w53 = cos( w8 );
  /* #301: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #302: @18 = mac(@22,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #303: @34 = @18' */
  for (i=0, rr=w34, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #304: {@12, NULL, @36} = horzsplit(@34) */
  casadi_copy(w34, 3, w12);
  casadi_copy(w34+6, 3, w36);
  /* #305: @12 = @12' */
  /* #306: {@57, NULL, @59} = horzsplit(@12) */
  w57 = w12[0];
  w59 = w12[2];
  /* #307: @59 = (@53*@59) */
  w59  = (w53*w59);
  /* #308: @60 = cos(@8) */
  w60 = cos( w8 );
  /* #309: @36 = @36' */
  /* #310: {@61, NULL, @62} = horzsplit(@36) */
  w61 = w36[0];
  w62 = w36[2];
  /* #311: @61 = (@60*@61) */
  w61  = (w60*w61);
  /* #312: @59 = (@59-@61) */
  w59 -= w61;
  /* #313: @59 = (-@59) */
  w59 = (- w59 );
  /* #314: @61 = sin(@8) */
  w61 = sin( w8 );
  /* #315: @62 = (@61*@62) */
  w62  = (w61*w62);
  /* #316: @59 = (@59-@62) */
  w59 -= w62;
  /* #317: @62 = sin(@8) */
  w62 = sin( w8 );
  /* #318: @57 = (@62*@57) */
  w57  = (w62*w57);
  /* #319: @59 = (@59-@57) */
  w59 -= w57;
  /* #320: (@0[7] = @59) */
  for (rr=w0+7, ss=(&w59); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #321: @59 = ones(3x1,1nz) */
  w59 = 1.;
  /* #322: {NULL, @57, NULL} = vertsplit(@59) */
  w57 = w59;
  /* #323: (@0[8] = @57) */
  for (rr=w0+8, ss=(&w57); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #324: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #325: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #326: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #327: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #328: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #329: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #330: @36 = @10' */
  casadi_copy(w10, 3, w36);
  /* #331: @63 = mac(@59,@36,@63) */
  casadi_mtimes((&w59), casadi_s4, w36, casadi_s1, w63, casadi_s0, w, 0);
  /* #332: @64 = @21' */
  for (i=0, rr=w64, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #333: @47 = mac(@63,@64,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w64+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #334: @63 = @20' */
  for (i=0, rr=w63, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #335: @19 = mac(@47,@63,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #336: @63 = @26' */
  for (i=0, rr=w63, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #337: @17 = mac(@19,@63,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #338: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #339: @36 = @11' */
  casadi_copy(w11, 3, w36);
  /* #340: @63 = mac(@59,@36,@63) */
  casadi_mtimes((&w59), casadi_s4, w36, casadi_s1, w63, casadi_s0, w, 0);
  /* #341: @17 = (@17+@63) */
  for (i=0, rr=w17, cs=w63; i<9; ++i) (*rr++) += (*cs++);
  /* #342: @34 = mac(@18,@17,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #343: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #344: {NULL, @36, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w36);
  casadi_copy(w18+6, 3, w12);
  /* #345: @12 = @12' */
  /* #346: {NULL, @57, @65} = horzsplit(@12) */
  w57 = w12[1];
  w65 = w12[2];
  /* #347: @57 = (@3*@57) */
  w57  = (w3*w57);
  /* #348: @65 = (@27*@65) */
  w65  = (w27*w65);
  /* #349: @57 = (@57-@65) */
  w57 -= w65;
  /* #350: @36 = @36' */
  /* #351: {NULL, @65, @66} = horzsplit(@36) */
  w65 = w36[1];
  w66 = w36[2];
  /* #352: @66 = (@31*@66) */
  w66  = (w31*w66);
  /* #353: @57 = (@57-@66) */
  w57 -= w66;
  /* #354: @65 = (@37*@65) */
  w65  = (w37*w65);
  /* #355: @57 = (@57-@65) */
  w57 -= w65;
  /* #356: (@0[9] = @57) */
  for (rr=w0+9, ss=(&w57); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #357: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #358: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #359: @34 = mac(@17,@30,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #360: @18 = mac(@13,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #361: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #362: {@36, NULL, @12} = horzsplit(@17) */
  casadi_copy(w17, 3, w36);
  casadi_copy(w17+6, 3, w12);
  /* #363: @12 = @12' */
  /* #364: {@57, NULL, @65} = horzsplit(@12) */
  w57 = w12[0];
  w65 = w12[2];
  /* #365: @57 = (@23*@57) */
  w57  = (w23*w57);
  /* #366: @57 = (-@57) */
  w57 = (- w57 );
  /* #367: @65 = (@39*@65) */
  w65  = (w39*w65);
  /* #368: @57 = (@57-@65) */
  w57 -= w65;
  /* #369: @36 = @36' */
  /* #370: {@65, NULL, @66} = horzsplit(@36) */
  w65 = w36[0];
  w66 = w36[2];
  /* #371: @66 = (@38*@66) */
  w66  = (w38*w66);
  /* #372: @57 = (@57+@66) */
  w57 += w66;
  /* #373: @65 = (@42*@65) */
  w65  = (w42*w65);
  /* #374: @57 = (@57-@65) */
  w57 -= w65;
  /* #375: (@0[10] = @57) */
  for (rr=w0+10, ss=(&w57); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #376: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #377: @17 = mac(@34,@16,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #378: @34 = @17' */
  for (i=0, rr=w34, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #379: {@36, @12, NULL} = horzsplit(@34) */
  casadi_copy(w34, 3, w36);
  casadi_copy(w34+3, 3, w12);
  /* #380: @12 = @12' */
  /* #381: {@57, @65, NULL} = horzsplit(@12) */
  w57 = w12[0];
  w65 = w12[1];
  /* #382: @32 = (@32*@57) */
  w32 *= w57;
  /* #383: @44 = (@44*@65) */
  w44 *= w65;
  /* #384: @32 = (@32-@44) */
  w32 -= w44;
  /* #385: @36 = @36' */
  /* #386: {@44, @65, NULL} = horzsplit(@36) */
  w44 = w36[0];
  w65 = w36[1];
  /* #387: @43 = (@43*@65) */
  w43 *= w65;
  /* #388: @32 = (@32-@43) */
  w32 -= w43;
  /* #389: @46 = (@46*@44) */
  w46 *= w44;
  /* #390: @32 = (@32-@46) */
  w32 -= w46;
  /* #391: (@0[11] = @32) */
  for (rr=w0+11, ss=(&w32); rr!=w0+12; rr+=1) *rr = *ss++;
  /* #392: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #393: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #394: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #395: @17 = mac(@18,@19,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #396: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #397: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #398: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #399: @63 = @14' */
  for (i=0, rr=w63, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #400: @36 = mac(@63,@59,@36) */
  casadi_mtimes(w63, casadi_s0, (&w59), casadi_s4, w36, casadi_s3, w, 0);
  /* #401: @12 = @25' */
  casadi_copy(w25, 3, w12);
  /* #402: @19 = mac(@36,@12,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w12+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #403: @63 = @35' */
  for (i=0, rr=w63, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #404: @18 = mac(@19,@63,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #405: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #406: @34 = mac(@29,@17,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #407: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #408: {NULL, @36, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w36);
  casadi_copy(w18+6, 3, w12);
  /* #409: @12 = @12' */
  /* #410: {NULL, @59, @32} = horzsplit(@12) */
  w59 = w12[1];
  w32 = w12[2];
  /* #411: @59 = (@41*@59) */
  w59  = (w41*w59);
  /* #412: @36 = @36' */
  /* #413: {NULL, @46, @44} = horzsplit(@36) */
  w46 = w36[1];
  w44 = w36[2];
  /* #414: @44 = (@48*@44) */
  w44  = (w48*w44);
  /* #415: @59 = (@59-@44) */
  w59 -= w44;
  /* #416: @59 = (-@59) */
  w59 = (- w59 );
  /* #417: @32 = (@50*@32) */
  w32  = (w50*w32);
  /* #418: @59 = (@59-@32) */
  w59 -= w32;
  /* #419: @46 = (@45*@46) */
  w46  = (w45*w46);
  /* #420: @59 = (@59-@46) */
  w59 -= w46;
  /* #421: (@0[12] = @59) */
  for (rr=w0+12, ss=(&w59); rr!=w0+13; rr+=1) *rr = *ss++;
  /* #422: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #423: @18 = mac(@17,@33,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #424: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #425: {@36, @12, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w36);
  casadi_copy(w17+3, 3, w12);
  /* #426: @12 = @12' */
  /* #427: {@59, @46, NULL} = horzsplit(@12) */
  w59 = w12[0];
  w46 = w12[1];
  /* #428: @59 = (@1*@59) */
  w59  = (w1*w59);
  /* #429: @46 = (@52*@46) */
  w46  = (w52*w46);
  /* #430: @59 = (@59-@46) */
  w59 -= w46;
  /* #431: @36 = @36' */
  /* #432: {@46, @32, NULL} = horzsplit(@36) */
  w46 = w36[0];
  w32 = w36[1];
  /* #433: @32 = (@51*@32) */
  w32  = (w51*w32);
  /* #434: @59 = (@59-@32) */
  w59 -= w32;
  /* #435: @46 = (@54*@46) */
  w46  = (w54*w46);
  /* #436: @59 = (@59-@46) */
  w59 -= w46;
  /* #437: (@0[13] = @59) */
  for (rr=w0+13, ss=(&w59); rr!=w0+14; rr+=1) *rr = *ss++;
  /* #438: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #439: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #440: @34 = @4' */
  for (i=0, rr=w34, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #441: @18 = mac(@34,@47,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #442: @17 = mac(@18,@28,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #443: @34 = @17' */
  for (i=0, rr=w34, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #444: {NULL, @36, @12} = horzsplit(@34) */
  casadi_copy(w34+3, 3, w36);
  casadi_copy(w34+6, 3, w12);
  /* #445: @12 = @12' */
  /* #446: {NULL, @59, @46} = horzsplit(@12) */
  w59 = w12[1];
  w46 = w12[2];
  /* #447: @59 = (@49*@59) */
  w59  = (w49*w59);
  /* #448: @36 = @36' */
  /* #449: {NULL, @32, @44} = horzsplit(@36) */
  w32 = w36[1];
  w44 = w36[2];
  /* #450: @44 = (@56*@44) */
  w44  = (w56*w44);
  /* #451: @59 = (@59-@44) */
  w59 -= w44;
  /* #452: @59 = (-@59) */
  w59 = (- w59 );
  /* #453: @46 = (@58*@46) */
  w46  = (w58*w46);
  /* #454: @59 = (@59-@46) */
  w59 -= w46;
  /* #455: @32 = (@55*@32) */
  w32  = (w55*w32);
  /* #456: @59 = (@59-@32) */
  w59 -= w32;
  /* #457: (@0[14] = @59) */
  for (rr=w0+14, ss=(&w59); rr!=w0+15; rr+=1) *rr = *ss++;
  /* #458: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #459: @34 = mac(@22,@18,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #460: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #461: {@36, NULL, @12} = horzsplit(@18) */
  casadi_copy(w18, 3, w36);
  casadi_copy(w18+6, 3, w12);
  /* #462: @36 = @36' */
  /* #463: {@59, NULL, @32} = horzsplit(@36) */
  w59 = w36[0];
  w32 = w36[2];
  /* #464: @32 = (@53*@32) */
  w32  = (w53*w32);
  /* #465: @12 = @12' */
  /* #466: {@46, NULL, @44} = horzsplit(@12) */
  w46 = w12[0];
  w44 = w12[2];
  /* #467: @46 = (@60*@46) */
  w46  = (w60*w46);
  /* #468: @32 = (@32-@46) */
  w32 -= w46;
  /* #469: @32 = (-@32) */
  w32 = (- w32 );
  /* #470: @44 = (@61*@44) */
  w44  = (w61*w44);
  /* #471: @32 = (@32-@44) */
  w32 -= w44;
  /* #472: @59 = (@62*@59) */
  w59  = (w62*w59);
  /* #473: @32 = (@32-@59) */
  w32 -= w59;
  /* #474: (@0[15] = @32) */
  for (rr=w0+15, ss=(&w32); rr!=w0+16; rr+=1) *rr = *ss++;
  /* #475: @32 = ones(3x1,1nz) */
  w32 = 1.;
  /* #476: {NULL, NULL, @59} = vertsplit(@32) */
  w59 = w32;
  /* #477: (@0[16] = @59) */
  for (rr=w0+16, ss=(&w59); rr!=w0+17; rr+=1) *rr = *ss++;
  /* #478: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #479: @34 = @5' */
  for (i=0, rr=w34, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #480: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #481: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #482: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #483: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #484: @12 = @10' */
  casadi_copy(w10, 3, w12);
  /* #485: @63 = mac(@32,@12,@63) */
  casadi_mtimes((&w32), casadi_s5, w12, casadi_s1, w63, casadi_s0, w, 0);
  /* #486: @64 = @21' */
  for (i=0, rr=w64, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #487: @19 = mac(@63,@64,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w64+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #488: @63 = @20' */
  for (i=0, rr=w63, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #489: @47 = mac(@19,@63,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #490: @63 = @26' */
  for (i=0, rr=w63, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #491: @17 = mac(@47,@63,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #492: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #493: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #494: @63 = mac(@32,@12,@63) */
  casadi_mtimes((&w32), casadi_s5, w12, casadi_s1, w63, casadi_s0, w, 0);
  /* #495: @17 = (@17+@63) */
  for (i=0, rr=w17, cs=w63; i<9; ++i) (*rr++) += (*cs++);
  /* #496: @18 = mac(@34,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #497: @34 = @18' */
  for (i=0, rr=w34, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #498: {NULL, @12, @36} = horzsplit(@34) */
  casadi_copy(w34+3, 3, w12);
  casadi_copy(w34+6, 3, w36);
  /* #499: @36 = @36' */
  /* #500: {NULL, @59, @44} = horzsplit(@36) */
  w59 = w36[1];
  w44 = w36[2];
  /* #501: @3 = (@3*@59) */
  w3 *= w59;
  /* #502: @27 = (@27*@44) */
  w27 *= w44;
  /* #503: @3 = (@3-@27) */
  w3 -= w27;
  /* #504: @12 = @12' */
  /* #505: {NULL, @27, @44} = horzsplit(@12) */
  w27 = w12[1];
  w44 = w12[2];
  /* #506: @31 = (@31*@44) */
  w31 *= w44;
  /* #507: @3 = (@3-@31) */
  w3 -= w31;
  /* #508: @37 = (@37*@27) */
  w37 *= w27;
  /* #509: @3 = (@3-@37) */
  w3 -= w37;
  /* #510: (@0[17] = @3) */
  for (rr=w0+17, ss=(&w3); rr!=w0+18; rr+=1) *rr = *ss++;
  /* #511: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #512: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #513: @18 = mac(@17,@30,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #514: @34 = mac(@13,@18,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #515: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #516: {@12, NULL, @36} = horzsplit(@18) */
  casadi_copy(w18, 3, w12);
  casadi_copy(w18+6, 3, w36);
  /* #517: @36 = @36' */
  /* #518: {@3, NULL, @37} = horzsplit(@36) */
  w3 = w36[0];
  w37 = w36[2];
  /* #519: @23 = (@23*@3) */
  w23 *= w3;
  /* #520: @23 = (-@23) */
  w23 = (- w23 );
  /* #521: @39 = (@39*@37) */
  w39 *= w37;
  /* #522: @23 = (@23-@39) */
  w23 -= w39;
  /* #523: @12 = @12' */
  /* #524: {@39, NULL, @37} = horzsplit(@12) */
  w39 = w12[0];
  w37 = w12[2];
  /* #525: @38 = (@38*@37) */
  w38 *= w37;
  /* #526: @23 = (@23+@38) */
  w23 += w38;
  /* #527: @42 = (@42*@39) */
  w42 *= w39;
  /* #528: @23 = (@23-@42) */
  w23 -= w42;
  /* #529: (@0[18] = @23) */
  for (rr=w0+18, ss=(&w23); rr!=w0+19; rr+=1) *rr = *ss++;
  /* #530: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #531: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #532: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #533: @34 = mac(@17,@47,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #534: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #535: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #536: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #537: @63 = @14' */
  for (i=0, rr=w63, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #538: @12 = mac(@63,@32,@12) */
  casadi_mtimes(w63, casadi_s0, (&w32), casadi_s5, w12, casadi_s3, w, 0);
  /* #539: @36 = @25' */
  casadi_copy(w25, 3, w36);
  /* #540: @47 = mac(@12,@36,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w36+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #541: @63 = @35' */
  for (i=0, rr=w63, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #542: @17 = mac(@47,@63,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #543: @34 = (@34+@17) */
  for (i=0, rr=w34, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #544: @18 = mac(@29,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #545: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #546: {NULL, @12, @36} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w12);
  casadi_copy(w17+6, 3, w36);
  /* #547: @36 = @36' */
  /* #548: {NULL, @32, @23} = horzsplit(@36) */
  w32 = w36[1];
  w23 = w36[2];
  /* #549: @41 = (@41*@32) */
  w41 *= w32;
  /* #550: @12 = @12' */
  /* #551: {NULL, @32, @42} = horzsplit(@12) */
  w32 = w12[1];
  w42 = w12[2];
  /* #552: @48 = (@48*@42) */
  w48 *= w42;
  /* #553: @41 = (@41-@48) */
  w41 -= w48;
  /* #554: @41 = (-@41) */
  w41 = (- w41 );
  /* #555: @50 = (@50*@23) */
  w50 *= w23;
  /* #556: @41 = (@41-@50) */
  w41 -= w50;
  /* #557: @45 = (@45*@32) */
  w45 *= w32;
  /* #558: @41 = (@41-@45) */
  w41 -= w45;
  /* #559: (@0[19] = @41) */
  for (rr=w0+19, ss=(&w41); rr!=w0+20; rr+=1) *rr = *ss++;
  /* #560: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #561: @17 = mac(@34,@33,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #562: @34 = @17' */
  for (i=0, rr=w34, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #563: {@12, @36, NULL} = horzsplit(@34) */
  casadi_copy(w34, 3, w12);
  casadi_copy(w34+3, 3, w36);
  /* #564: @36 = @36' */
  /* #565: {@41, @45, NULL} = horzsplit(@36) */
  w41 = w36[0];
  w45 = w36[1];
  /* #566: @1 = (@1*@41) */
  w1 *= w41;
  /* #567: @52 = (@52*@45) */
  w52 *= w45;
  /* #568: @1 = (@1-@52) */
  w1 -= w52;
  /* #569: @12 = @12' */
  /* #570: {@52, @45, NULL} = horzsplit(@12) */
  w52 = w12[0];
  w45 = w12[1];
  /* #571: @51 = (@51*@45) */
  w51 *= w45;
  /* #572: @1 = (@1-@51) */
  w1 -= w51;
  /* #573: @54 = (@54*@52) */
  w54 *= w52;
  /* #574: @1 = (@1-@54) */
  w1 -= w54;
  /* #575: (@0[20] = @1) */
  for (rr=w0+20, ss=(&w1); rr!=w0+21; rr+=1) *rr = *ss++;
  /* #576: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #577: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #578: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #579: @17 = mac(@18,@19,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #580: @34 = mac(@17,@28,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #581: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #582: {NULL, @12, @36} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w36);
  /* #583: @36 = @36' */
  /* #584: {NULL, @1, @54} = horzsplit(@36) */
  w1 = w36[1];
  w54 = w36[2];
  /* #585: @49 = (@49*@1) */
  w49 *= w1;
  /* #586: @12 = @12' */
  /* #587: {NULL, @1, @52} = horzsplit(@12) */
  w1 = w12[1];
  w52 = w12[2];
  /* #588: @56 = (@56*@52) */
  w56 *= w52;
  /* #589: @49 = (@49-@56) */
  w49 -= w56;
  /* #590: @49 = (-@49) */
  w49 = (- w49 );
  /* #591: @58 = (@58*@54) */
  w58 *= w54;
  /* #592: @49 = (@49-@58) */
  w49 -= w58;
  /* #593: @55 = (@55*@1) */
  w55 *= w1;
  /* #594: @49 = (@49-@55) */
  w49 -= w55;
  /* #595: (@0[21] = @49) */
  for (rr=w0+21, ss=(&w49); rr!=w0+22; rr+=1) *rr = *ss++;
  /* #596: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #597: @18 = mac(@22,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #598: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #599: {@12, NULL, @36} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+6, 3, w36);
  /* #600: @12 = @12' */
  /* #601: {@49, NULL, @55} = horzsplit(@12) */
  w49 = w12[0];
  w55 = w12[2];
  /* #602: @53 = (@53*@55) */
  w53 *= w55;
  /* #603: @36 = @36' */
  /* #604: {@55, NULL, @1} = horzsplit(@36) */
  w55 = w36[0];
  w1 = w36[2];
  /* #605: @60 = (@60*@55) */
  w60 *= w55;
  /* #606: @53 = (@53-@60) */
  w53 -= w60;
  /* #607: @53 = (-@53) */
  w53 = (- w53 );
  /* #608: @61 = (@61*@1) */
  w61 *= w1;
  /* #609: @53 = (@53-@61) */
  w53 -= w61;
  /* #610: @62 = (@62*@49) */
  w62 *= w49;
  /* #611: @53 = (@53-@62) */
  w53 -= w62;
  /* #612: (@0[22] = @53) */
  for (rr=w0+22, ss=(&w53); rr!=w0+23; rr+=1) *rr = *ss++;
  /* #613: output[0][0] = @0 */
  casadi_copy(w0, 23, res[0]);
  /* #614: @36 = zeros(3x1) */
  casadi_clear(w36, 3);
  /* #615: @0 = zeros(14x3,23nz) */
  casadi_clear(w0, 23);
  /* #616: @53 = ones(3x1,1nz) */
  w53 = 1.;
  /* #617: {@62, NULL, NULL} = vertsplit(@53) */
  w62 = w53;
  /* #618: (@0[0] = @62) */
  for (rr=w0+0, ss=(&w62); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #619: @62 = cos(@2) */
  w62 = cos( w2 );
  /* #620: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #621: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #622: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #623: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #624: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #625: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #626: @12 = @10' */
  casadi_copy(w10, 3, w12);
  /* #627: @63 = mac(@53,@12,@63) */
  casadi_mtimes((&w53), casadi_s2, w12, casadi_s1, w63, casadi_s0, w, 0);
  /* #628: @64 = @21' */
  for (i=0, rr=w64, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #629: @47 = mac(@63,@64,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w64+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #630: @63 = @20' */
  for (i=0, rr=w63, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #631: @19 = mac(@47,@63,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #632: @63 = @26' */
  for (i=0, rr=w63, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #633: @34 = mac(@19,@63,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #634: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #635: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #636: @63 = mac(@53,@12,@63) */
  casadi_mtimes((&w53), casadi_s2, w12, casadi_s1, w63, casadi_s0, w, 0);
  /* #637: @34 = (@34+@63) */
  for (i=0, rr=w34, cs=w63; i<9; ++i) (*rr++) += (*cs++);
  /* #638: @17 = mac(@18,@34,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #639: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #640: {NULL, @12, @40} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w40);
  /* #641: @40 = @40' */
  /* #642: {NULL, @49, @61} = horzsplit(@40) */
  w49 = w40[1];
  w61 = w40[2];
  /* #643: @49 = (@62*@49) */
  w49  = (w62*w49);
  /* #644: @1 = sin(@2) */
  w1 = sin( w2 );
  /* #645: @61 = (@1*@61) */
  w61  = (w1*w61);
  /* #646: @49 = (@49-@61) */
  w49 -= w61;
  /* #647: @61 = cos(@2) */
  w61 = cos( w2 );
  /* #648: @12 = @12' */
  /* #649: {NULL, @60, @55} = horzsplit(@12) */
  w60 = w12[1];
  w55 = w12[2];
  /* #650: @55 = (@61*@55) */
  w55  = (w61*w55);
  /* #651: @49 = (@49-@55) */
  w49 -= w55;
  /* #652: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #653: @60 = (@2*@60) */
  w60  = (w2*w60);
  /* #654: @49 = (@49-@60) */
  w49 -= w60;
  /* #655: (@0[1] = @49) */
  for (rr=w0+1, ss=(&w49); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #656: @49 = cos(@7) */
  w49 = cos( w7 );
  /* #657: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #658: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #659: @17 = mac(@34,@30,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #660: @18 = mac(@13,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #661: @34 = @18' */
  for (i=0, rr=w34, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #662: {@12, NULL, @40} = horzsplit(@34) */
  casadi_copy(w34, 3, w12);
  casadi_copy(w34+6, 3, w40);
  /* #663: @40 = @40' */
  /* #664: {@60, NULL, @55} = horzsplit(@40) */
  w60 = w40[0];
  w55 = w40[2];
  /* #665: @60 = (@49*@60) */
  w60  = (w49*w60);
  /* #666: @60 = (-@60) */
  w60 = (- w60 );
  /* #667: @58 = sin(@7) */
  w58 = sin( w7 );
  /* #668: @55 = (@58*@55) */
  w55  = (w58*w55);
  /* #669: @60 = (@60-@55) */
  w60 -= w55;
  /* #670: @55 = cos(@7) */
  w55 = cos( w7 );
  /* #671: @12 = @12' */
  /* #672: {@54, NULL, @56} = horzsplit(@12) */
  w54 = w12[0];
  w56 = w12[2];
  /* #673: @56 = (@55*@56) */
  w56  = (w55*w56);
  /* #674: @60 = (@60+@56) */
  w60 += w56;
  /* #675: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #676: @54 = (@7*@54) */
  w54  = (w7*w54);
  /* #677: @60 = (@60-@54) */
  w60 -= w54;
  /* #678: (@0[2] = @60) */
  for (rr=w0+2, ss=(&w60); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #679: @60 = cos(@6) */
  w60 = cos( w6 );
  /* #680: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #681: @34 = mac(@17,@16,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #682: @17 = @34' */
  for (i=0, rr=w17, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #683: {@12, @40, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+3, 3, w40);
  /* #684: @40 = @40' */
  /* #685: {@54, @56, NULL} = horzsplit(@40) */
  w54 = w40[0];
  w56 = w40[1];
  /* #686: @54 = (@60*@54) */
  w54  = (w60*w54);
  /* #687: @52 = sin(@6) */
  w52 = sin( w6 );
  /* #688: @56 = (@52*@56) */
  w56  = (w52*w56);
  /* #689: @54 = (@54-@56) */
  w54 -= w56;
  /* #690: @56 = cos(@6) */
  w56 = cos( w6 );
  /* #691: @12 = @12' */
  /* #692: {@51, @45, NULL} = horzsplit(@12) */
  w51 = w12[0];
  w45 = w12[1];
  /* #693: @45 = (@56*@45) */
  w45  = (w56*w45);
  /* #694: @54 = (@54-@45) */
  w54 -= w45;
  /* #695: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #696: @51 = (@6*@51) */
  w51  = (w6*w51);
  /* #697: @54 = (@54-@51) */
  w54 -= w51;
  /* #698: (@0[3] = @54) */
  for (rr=w0+3, ss=(&w54); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #699: @54 = cos(@15) */
  w54 = cos( w15 );
  /* #700: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #701: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #702: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #703: @34 = mac(@18,@19,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #704: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #705: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #706: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #707: @63 = @14' */
  for (i=0, rr=w63, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #708: @12 = mac(@63,@53,@12) */
  casadi_mtimes(w63, casadi_s0, (&w53), casadi_s2, w12, casadi_s3, w, 0);
  /* #709: @40 = @25' */
  casadi_copy(w25, 3, w40);
  /* #710: @19 = mac(@12,@40,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w40+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #711: @63 = @35' */
  for (i=0, rr=w63, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #712: @18 = mac(@19,@63,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #713: @34 = (@34+@18) */
  for (i=0, rr=w34, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #714: @17 = mac(@29,@34,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #715: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #716: {NULL, @12, @40} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w40);
  /* #717: @40 = @40' */
  /* #718: {NULL, @53, @51} = horzsplit(@40) */
  w53 = w40[1];
  w51 = w40[2];
  /* #719: @53 = (@54*@53) */
  w53  = (w54*w53);
  /* #720: @45 = cos(@15) */
  w45 = cos( w15 );
  /* #721: @12 = @12' */
  /* #722: {NULL, @41, @32} = horzsplit(@12) */
  w41 = w12[1];
  w32 = w12[2];
  /* #723: @32 = (@45*@32) */
  w32  = (w45*w32);
  /* #724: @53 = (@53-@32) */
  w53 -= w32;
  /* #725: @53 = (-@53) */
  w53 = (- w53 );
  /* #726: @32 = sin(@15) */
  w32 = sin( w15 );
  /* #727: @51 = (@32*@51) */
  w51  = (w32*w51);
  /* #728: @53 = (@53-@51) */
  w53 -= w51;
  /* #729: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #730: @41 = (@15*@41) */
  w41  = (w15*w41);
  /* #731: @53 = (@53-@41) */
  w53 -= w41;
  /* #732: (@0[4] = @53) */
  for (rr=w0+4, ss=(&w53); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #733: @53 = cos(@24) */
  w53 = cos( w24 );
  /* #734: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #735: @18 = mac(@34,@33,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #736: @34 = @18' */
  for (i=0, rr=w34, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #737: {@12, @40, NULL} = horzsplit(@34) */
  casadi_copy(w34, 3, w12);
  casadi_copy(w34+3, 3, w40);
  /* #738: @40 = @40' */
  /* #739: {@41, @51, NULL} = horzsplit(@40) */
  w41 = w40[0];
  w51 = w40[1];
  /* #740: @41 = (@53*@41) */
  w41  = (w53*w41);
  /* #741: @50 = sin(@24) */
  w50 = sin( w24 );
  /* #742: @51 = (@50*@51) */
  w51  = (w50*w51);
  /* #743: @41 = (@41-@51) */
  w41 -= w51;
  /* #744: @51 = cos(@24) */
  w51 = cos( w24 );
  /* #745: @12 = @12' */
  /* #746: {@23, @48, NULL} = horzsplit(@12) */
  w23 = w12[0];
  w48 = w12[1];
  /* #747: @48 = (@51*@48) */
  w48  = (w51*w48);
  /* #748: @41 = (@41-@48) */
  w41 -= w48;
  /* #749: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #750: @23 = (@24*@23) */
  w23  = (w24*w23);
  /* #751: @41 = (@41-@23) */
  w41 -= w23;
  /* #752: (@0[5] = @41) */
  for (rr=w0+5, ss=(&w41); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #753: @41 = cos(@9) */
  w41 = cos( w9 );
  /* #754: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #755: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #756: @17 = @4' */
  for (i=0, rr=w17, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #757: @18 = mac(@17,@47,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #758: @34 = mac(@18,@28,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #759: @17 = @34' */
  for (i=0, rr=w17, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #760: {NULL, @12, @40} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w12);
  casadi_copy(w17+6, 3, w40);
  /* #761: @40 = @40' */
  /* #762: {NULL, @23, @48} = horzsplit(@40) */
  w23 = w40[1];
  w48 = w40[2];
  /* #763: @23 = (@41*@23) */
  w23  = (w41*w23);
  /* #764: @42 = cos(@9) */
  w42 = cos( w9 );
  /* #765: @12 = @12' */
  /* #766: {NULL, @39, @38} = horzsplit(@12) */
  w39 = w12[1];
  w38 = w12[2];
  /* #767: @38 = (@42*@38) */
  w38  = (w42*w38);
  /* #768: @23 = (@23-@38) */
  w23 -= w38;
  /* #769: @23 = (-@23) */
  w23 = (- w23 );
  /* #770: @38 = sin(@9) */
  w38 = sin( w9 );
  /* #771: @48 = (@38*@48) */
  w48  = (w38*w48);
  /* #772: @23 = (@23-@48) */
  w23 -= w48;
  /* #773: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #774: @39 = (@9*@39) */
  w39  = (w9*w39);
  /* #775: @23 = (@23-@39) */
  w23 -= w39;
  /* #776: (@0[6] = @23) */
  for (rr=w0+6, ss=(&w23); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #777: @23 = cos(@8) */
  w23 = cos( w8 );
  /* #778: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #779: @17 = mac(@22,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #780: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #781: {@12, NULL, @40} = horzsplit(@18) */
  casadi_copy(w18, 3, w12);
  casadi_copy(w18+6, 3, w40);
  /* #782: @12 = @12' */
  /* #783: {@39, NULL, @48} = horzsplit(@12) */
  w39 = w12[0];
  w48 = w12[2];
  /* #784: @48 = (@23*@48) */
  w48  = (w23*w48);
  /* #785: @37 = cos(@8) */
  w37 = cos( w8 );
  /* #786: @40 = @40' */
  /* #787: {@3, NULL, @27} = horzsplit(@40) */
  w3 = w40[0];
  w27 = w40[2];
  /* #788: @3 = (@37*@3) */
  w3  = (w37*w3);
  /* #789: @48 = (@48-@3) */
  w48 -= w3;
  /* #790: @48 = (-@48) */
  w48 = (- w48 );
  /* #791: @3 = sin(@8) */
  w3 = sin( w8 );
  /* #792: @27 = (@3*@27) */
  w27  = (w3*w27);
  /* #793: @48 = (@48-@27) */
  w48 -= w27;
  /* #794: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #795: @39 = (@8*@39) */
  w39  = (w8*w39);
  /* #796: @48 = (@48-@39) */
  w48 -= w39;
  /* #797: (@0[7] = @48) */
  for (rr=w0+7, ss=(&w48); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #798: @48 = ones(3x1,1nz) */
  w48 = 1.;
  /* #799: {NULL, @39, NULL} = vertsplit(@48) */
  w39 = w48;
  /* #800: (@0[8] = @39) */
  for (rr=w0+8, ss=(&w39); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #801: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #802: @17 = @5' */
  for (i=0, rr=w17, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #803: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #804: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #805: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #806: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #807: @40 = @10' */
  casadi_copy(w10, 3, w40);
  /* #808: @63 = mac(@48,@40,@63) */
  casadi_mtimes((&w48), casadi_s4, w40, casadi_s1, w63, casadi_s0, w, 0);
  /* #809: @64 = @21' */
  for (i=0, rr=w64, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #810: @19 = mac(@63,@64,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w64+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #811: @63 = @20' */
  for (i=0, rr=w63, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #812: @47 = mac(@19,@63,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #813: @63 = @26' */
  for (i=0, rr=w63, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #814: @34 = mac(@47,@63,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w63+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #815: @63 = zeros(3x3) */
  casadi_clear(w63, 9);
  /* #816: @40 = @11' */
  casadi_copy(w11, 3, w40);
  /* #817: @63 = mac(@48,@40,@63) */
  casadi_mtimes((&w48), casadi_s4, w40, casadi_s1, w63, casadi_s0, w, 0);
  /* #818: @34 = (@34+@63) */
  for (i=0, rr=w34, cs=w63; i<9; ++i) (*rr++) += (*cs++);
  /* #819: @18 = mac(@17,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #820: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #821: {NULL, @40, @12} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w40);
  casadi_copy(w17+6, 3, w12);
  /* #822: @12 = @12' */
  /* #823: {NULL, @39, @27} = horzsplit(@12) */
  w39 = w12[1];
  w27 = w12[2];
  /* #824: @39 = (@62*@39) */
  w39  = (w62*w39);
  /* #825: @27 = (@1*@27) */
  w27  = (w1*w27);
  /* #826: @39 = (@39-@27) */
  w39 -= w27;
  /* #827: @40 = @40' */
  /* #828: {NULL, @27, @31} = horzsplit(@40) */
  w27 = w40[1];
  w31 = w40[2];
  /* #829: @31 = (@61*@31) */
  w31  = (w61*w31);
  /* #830: @39 = (@39-@31) */
  w39 -= w31;
  /* #831: @27 = (@2*@27) */
  w27  = (w2*w27);
  /* #832: @39 = (@39-@27) */
  w39 -= w27;
  /* #833: (@0[9] = @39) */
  for (rr=w0+9, ss=(&w39); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #834: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #835: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #836: @18 = mac(@34,@30,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #837: @17 = mac(@13,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #838: @34 = @17' */
  for (i=0, rr=w34, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #839: {@40, NULL, @12} = horzsplit(@34) */
  casadi_copy(w34, 3, w40);
  casadi_copy(w34+6, 3, w12);
  /* #840: @12 = @12' */
  /* #841: {@39, NULL, @27} = horzsplit(@12) */
  w39 = w12[0];
  w27 = w12[2];
  /* #842: @39 = (@49*@39) */
  w39  = (w49*w39);
  /* #843: @39 = (-@39) */
  w39 = (- w39 );
  /* #844: @27 = (@58*@27) */
  w27  = (w58*w27);
  /* #845: @39 = (@39-@27) */
  w39 -= w27;
  /* #846: @40 = @40' */
  /* #847: {@27, NULL, @31} = horzsplit(@40) */
  w27 = w40[0];
  w31 = w40[2];
  /* #848: @31 = (@55*@31) */
  w31  = (w55*w31);
  /* #849: @39 = (@39+@31) */
  w39 += w31;
  /* #850: @27 = (@7*@27) */
  w27  = (w7*w27);
  /* #851: @39 = (@39-@27) */
  w39 -= w27;
  /* #852: (@0[10] = @39) */
  for (rr=w0+10, ss=(&w39); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #853: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #854: @34 = mac(@18,@16,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #855: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #856: {@40, @12, NULL} = horzsplit(@18) */
  casadi_copy(w18, 3, w40);
  casadi_copy(w18+3, 3, w12);
  /* #857: @12 = @12' */
  /* #858: {@39, @27, NULL} = horzsplit(@12) */
  w39 = w12[0];
  w27 = w12[1];
  /* #859: @60 = (@60*@39) */
  w60 *= w39;
  /* #860: @52 = (@52*@27) */
  w52 *= w27;
  /* #861: @60 = (@60-@52) */
  w60 -= w52;
  /* #862: @40 = @40' */
  /* #863: {@52, @27, NULL} = horzsplit(@40) */
  w52 = w40[0];
  w27 = w40[1];
  /* #864: @56 = (@56*@27) */
  w56 *= w27;
  /* #865: @60 = (@60-@56) */
  w60 -= w56;
  /* #866: @6 = (@6*@52) */
  w6 *= w52;
  /* #867: @60 = (@60-@6) */
  w60 -= w6;
  /* #868: (@0[11] = @60) */
  for (rr=w0+11, ss=(&w60); rr!=w0+12; rr+=1) *rr = *ss++;
  /* #869: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #870: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #871: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #872: @34 = mac(@16,@47,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #873: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #874: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #875: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #876: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #877: @40 = mac(@17,@48,@40) */
  casadi_mtimes(w17, casadi_s0, (&w48), casadi_s4, w40, casadi_s3, w, 0);
  /* #878: @12 = @25' */
  casadi_copy(w25, 3, w12);
  /* #879: @47 = mac(@40,@12,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w40+j, tt=w12+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #880: @17 = @35' */
  for (i=0, rr=w17, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #881: @16 = mac(@47,@17,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #882: @34 = (@34+@16) */
  for (i=0, rr=w34, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #883: @18 = mac(@29,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #884: @16 = @18' */
  for (i=0, rr=w16, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #885: {NULL, @40, @12} = horzsplit(@16) */
  casadi_copy(w16+3, 3, w40);
  casadi_copy(w16+6, 3, w12);
  /* #886: @12 = @12' */
  /* #887: {NULL, @48, @60} = horzsplit(@12) */
  w48 = w12[1];
  w60 = w12[2];
  /* #888: @48 = (@54*@48) */
  w48  = (w54*w48);
  /* #889: @40 = @40' */
  /* #890: {NULL, @6, @52} = horzsplit(@40) */
  w6 = w40[1];
  w52 = w40[2];
  /* #891: @52 = (@45*@52) */
  w52  = (w45*w52);
  /* #892: @48 = (@48-@52) */
  w48 -= w52;
  /* #893: @48 = (-@48) */
  w48 = (- w48 );
  /* #894: @60 = (@32*@60) */
  w60  = (w32*w60);
  /* #895: @48 = (@48-@60) */
  w48 -= w60;
  /* #896: @6 = (@15*@6) */
  w6  = (w15*w6);
  /* #897: @48 = (@48-@6) */
  w48 -= w6;
  /* #898: (@0[12] = @48) */
  for (rr=w0+12, ss=(&w48); rr!=w0+13; rr+=1) *rr = *ss++;
  /* #899: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #900: @16 = mac(@34,@33,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #901: @34 = @16' */
  for (i=0, rr=w34, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #902: {@40, @12, NULL} = horzsplit(@34) */
  casadi_copy(w34, 3, w40);
  casadi_copy(w34+3, 3, w12);
  /* #903: @12 = @12' */
  /* #904: {@48, @6, NULL} = horzsplit(@12) */
  w48 = w12[0];
  w6 = w12[1];
  /* #905: @48 = (@53*@48) */
  w48  = (w53*w48);
  /* #906: @6 = (@50*@6) */
  w6  = (w50*w6);
  /* #907: @48 = (@48-@6) */
  w48 -= w6;
  /* #908: @40 = @40' */
  /* #909: {@6, @60, NULL} = horzsplit(@40) */
  w6 = w40[0];
  w60 = w40[1];
  /* #910: @60 = (@51*@60) */
  w60  = (w51*w60);
  /* #911: @48 = (@48-@60) */
  w48 -= w60;
  /* #912: @6 = (@24*@6) */
  w6  = (w24*w6);
  /* #913: @48 = (@48-@6) */
  w48 -= w6;
  /* #914: (@0[13] = @48) */
  for (rr=w0+13, ss=(&w48); rr!=w0+14; rr+=1) *rr = *ss++;
  /* #915: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #916: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #917: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #918: @16 = mac(@18,@19,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #919: @34 = mac(@16,@28,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #920: @18 = @34' */
  for (i=0, rr=w18, cs=w34; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #921: {NULL, @40, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w40);
  casadi_copy(w18+6, 3, w12);
  /* #922: @12 = @12' */
  /* #923: {NULL, @48, @6} = horzsplit(@12) */
  w48 = w12[1];
  w6 = w12[2];
  /* #924: @48 = (@41*@48) */
  w48  = (w41*w48);
  /* #925: @40 = @40' */
  /* #926: {NULL, @60, @52} = horzsplit(@40) */
  w60 = w40[1];
  w52 = w40[2];
  /* #927: @52 = (@42*@52) */
  w52  = (w42*w52);
  /* #928: @48 = (@48-@52) */
  w48 -= w52;
  /* #929: @48 = (-@48) */
  w48 = (- w48 );
  /* #930: @6 = (@38*@6) */
  w6  = (w38*w6);
  /* #931: @48 = (@48-@6) */
  w48 -= w6;
  /* #932: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #933: @48 = (@48-@60) */
  w48 -= w60;
  /* #934: (@0[14] = @48) */
  for (rr=w0+14, ss=(&w48); rr!=w0+15; rr+=1) *rr = *ss++;
  /* #935: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #936: @18 = mac(@22,@16,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #937: @16 = @18' */
  for (i=0, rr=w16, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #938: {@40, NULL, @12} = horzsplit(@16) */
  casadi_copy(w16, 3, w40);
  casadi_copy(w16+6, 3, w12);
  /* #939: @40 = @40' */
  /* #940: {@48, NULL, @60} = horzsplit(@40) */
  w48 = w40[0];
  w60 = w40[2];
  /* #941: @60 = (@23*@60) */
  w60  = (w23*w60);
  /* #942: @12 = @12' */
  /* #943: {@6, NULL, @52} = horzsplit(@12) */
  w6 = w12[0];
  w52 = w12[2];
  /* #944: @6 = (@37*@6) */
  w6  = (w37*w6);
  /* #945: @60 = (@60-@6) */
  w60 -= w6;
  /* #946: @60 = (-@60) */
  w60 = (- w60 );
  /* #947: @52 = (@3*@52) */
  w52  = (w3*w52);
  /* #948: @60 = (@60-@52) */
  w60 -= w52;
  /* #949: @48 = (@8*@48) */
  w48  = (w8*w48);
  /* #950: @60 = (@60-@48) */
  w60 -= w48;
  /* #951: (@0[15] = @60) */
  for (rr=w0+15, ss=(&w60); rr!=w0+16; rr+=1) *rr = *ss++;
  /* #952: @60 = ones(3x1,1nz) */
  w60 = 1.;
  /* #953: {NULL, NULL, @48} = vertsplit(@60) */
  w48 = w60;
  /* #954: (@0[16] = @48) */
  for (rr=w0+16, ss=(&w48); rr!=w0+17; rr+=1) *rr = *ss++;
  /* #955: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #956: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #957: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #958: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #959: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #960: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #961: @10 = @10' */
  /* #962: @47 = mac(@60,@10,@47) */
  casadi_mtimes((&w60), casadi_s5, w10, casadi_s1, w47, casadi_s0, w, 0);
  /* #963: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #964: @19 = mac(@47,@17,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w47+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #965: @47 = @20' */
  for (i=0, rr=w47, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #966: @34 = mac(@19,@47,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #967: @47 = @26' */
  for (i=0, rr=w47, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #968: @5 = mac(@34,@47,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #969: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #970: @11 = @11' */
  /* #971: @47 = mac(@60,@11,@47) */
  casadi_mtimes((&w60), casadi_s5, w11, casadi_s1, w47, casadi_s0, w, 0);
  /* #972: @5 = (@5+@47) */
  for (i=0, rr=w5, cs=w47; i<9; ++i) (*rr++) += (*cs++);
  /* #973: @16 = mac(@18,@5,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #974: @18 = @16' */
  for (i=0, rr=w18, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #975: {NULL, @11, @10} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w11);
  casadi_copy(w18+6, 3, w10);
  /* #976: @10 = @10' */
  /* #977: {NULL, @48, @52} = horzsplit(@10) */
  w48 = w10[1];
  w52 = w10[2];
  /* #978: @62 = (@62*@48) */
  w62 *= w48;
  /* #979: @1 = (@1*@52) */
  w1 *= w52;
  /* #980: @62 = (@62-@1) */
  w62 -= w1;
  /* #981: @11 = @11' */
  /* #982: {NULL, @1, @52} = horzsplit(@11) */
  w1 = w11[1];
  w52 = w11[2];
  /* #983: @61 = (@61*@52) */
  w61 *= w52;
  /* #984: @62 = (@62-@61) */
  w62 -= w61;
  /* #985: @2 = (@2*@1) */
  w2 *= w1;
  /* #986: @62 = (@62-@2) */
  w62 -= w2;
  /* #987: (@0[17] = @62) */
  for (rr=w0+17, ss=(&w62); rr!=w0+18; rr+=1) *rr = *ss++;
  /* #988: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #989: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #990: @16 = mac(@5,@30,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #991: @18 = mac(@13,@16,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #992: @13 = @18' */
  for (i=0, rr=w13, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #993: {@11, NULL, @10} = horzsplit(@13) */
  casadi_copy(w13, 3, w11);
  casadi_copy(w13+6, 3, w10);
  /* #994: @10 = @10' */
  /* #995: {@62, NULL, @2} = horzsplit(@10) */
  w62 = w10[0];
  w2 = w10[2];
  /* #996: @49 = (@49*@62) */
  w49 *= w62;
  /* #997: @49 = (-@49) */
  w49 = (- w49 );
  /* #998: @58 = (@58*@2) */
  w58 *= w2;
  /* #999: @49 = (@49-@58) */
  w49 -= w58;
  /* #1000: @11 = @11' */
  /* #1001: {@58, NULL, @2} = horzsplit(@11) */
  w58 = w11[0];
  w2 = w11[2];
  /* #1002: @55 = (@55*@2) */
  w55 *= w2;
  /* #1003: @49 = (@49+@55) */
  w49 += w55;
  /* #1004: @7 = (@7*@58) */
  w7 *= w58;
  /* #1005: @49 = (@49-@7) */
  w49 -= w7;
  /* #1006: (@0[18] = @49) */
  for (rr=w0+18, ss=(&w49); rr!=w0+19; rr+=1) *rr = *ss++;
  /* #1007: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #1008: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #1009: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1010: @18 = mac(@16,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1011: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #1012: @34 = zeros(3x3) */
  casadi_clear(w34, 9);
  /* #1013: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #1014: @5 = @14' */
  for (i=0, rr=w5, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1015: @11 = mac(@5,@60,@11) */
  casadi_mtimes(w5, casadi_s0, (&w60), casadi_s5, w11, casadi_s3, w, 0);
  /* #1016: @25 = @25' */
  /* #1017: @34 = mac(@11,@25,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #1018: @5 = @35' */
  for (i=0, rr=w5, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1019: @16 = mac(@34,@5,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w34+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1020: @18 = (@18+@16) */
  for (i=0, rr=w18, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #1021: @13 = mac(@29,@18,@13) */
  for (i=0, rr=w13; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1022: @29 = @13' */
  for (i=0, rr=w29, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1023: {NULL, @11, @25} = horzsplit(@29) */
  casadi_copy(w29+3, 3, w11);
  casadi_copy(w29+6, 3, w25);
  /* #1024: @25 = @25' */
  /* #1025: {NULL, @60, @49} = horzsplit(@25) */
  w60 = w25[1];
  w49 = w25[2];
  /* #1026: @54 = (@54*@60) */
  w54 *= w60;
  /* #1027: @11 = @11' */
  /* #1028: {NULL, @60, @7} = horzsplit(@11) */
  w60 = w11[1];
  w7 = w11[2];
  /* #1029: @45 = (@45*@7) */
  w45 *= w7;
  /* #1030: @54 = (@54-@45) */
  w54 -= w45;
  /* #1031: @54 = (-@54) */
  w54 = (- w54 );
  /* #1032: @32 = (@32*@49) */
  w32 *= w49;
  /* #1033: @54 = (@54-@32) */
  w54 -= w32;
  /* #1034: @15 = (@15*@60) */
  w15 *= w60;
  /* #1035: @54 = (@54-@15) */
  w54 -= w15;
  /* #1036: (@0[19] = @54) */
  for (rr=w0+19, ss=(&w54); rr!=w0+20; rr+=1) *rr = *ss++;
  /* #1037: @29 = zeros(3x3) */
  casadi_clear(w29, 9);
  /* #1038: @29 = mac(@18,@33,@29) */
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1039: @18 = @29' */
  for (i=0, rr=w18, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1040: {@11, @25, NULL} = horzsplit(@18) */
  casadi_copy(w18, 3, w11);
  casadi_copy(w18+3, 3, w25);
  /* #1041: @25 = @25' */
  /* #1042: {@54, @15, NULL} = horzsplit(@25) */
  w54 = w25[0];
  w15 = w25[1];
  /* #1043: @53 = (@53*@54) */
  w53 *= w54;
  /* #1044: @50 = (@50*@15) */
  w50 *= w15;
  /* #1045: @53 = (@53-@50) */
  w53 -= w50;
  /* #1046: @11 = @11' */
  /* #1047: {@50, @15, NULL} = horzsplit(@11) */
  w50 = w11[0];
  w15 = w11[1];
  /* #1048: @51 = (@51*@15) */
  w51 *= w15;
  /* #1049: @53 = (@53-@51) */
  w53 -= w51;
  /* #1050: @24 = (@24*@50) */
  w24 *= w50;
  /* #1051: @53 = (@53-@24) */
  w53 -= w24;
  /* #1052: (@0[20] = @53) */
  for (rr=w0+20, ss=(&w53); rr!=w0+21; rr+=1) *rr = *ss++;
  /* #1053: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #1054: @29 = zeros(3x3) */
  casadi_clear(w29, 9);
  /* #1055: @33 = @4' */
  for (i=0, rr=w33, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1056: @29 = mac(@33,@19,@29) */
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1057: @18 = mac(@29,@28,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1058: @28 = @18' */
  for (i=0, rr=w28, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1059: {NULL, @11, @25} = horzsplit(@28) */
  casadi_copy(w28+3, 3, w11);
  casadi_copy(w28+6, 3, w25);
  /* #1060: @25 = @25' */
  /* #1061: {NULL, @53, @24} = horzsplit(@25) */
  w53 = w25[1];
  w24 = w25[2];
  /* #1062: @41 = (@41*@53) */
  w41 *= w53;
  /* #1063: @11 = @11' */
  /* #1064: {NULL, @53, @50} = horzsplit(@11) */
  w53 = w11[1];
  w50 = w11[2];
  /* #1065: @42 = (@42*@50) */
  w42 *= w50;
  /* #1066: @41 = (@41-@42) */
  w41 -= w42;
  /* #1067: @41 = (-@41) */
  w41 = (- w41 );
  /* #1068: @38 = (@38*@24) */
  w38 *= w24;
  /* #1069: @41 = (@41-@38) */
  w41 -= w38;
  /* #1070: @9 = (@9*@53) */
  w9 *= w53;
  /* #1071: @41 = (@41-@9) */
  w41 -= w9;
  /* #1072: (@0[21] = @41) */
  for (rr=w0+21, ss=(&w41); rr!=w0+22; rr+=1) *rr = *ss++;
  /* #1073: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #1074: @28 = mac(@22,@29,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1075: @22 = @28' */
  for (i=0, rr=w22, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1076: {@11, NULL, @25} = horzsplit(@22) */
  casadi_copy(w22, 3, w11);
  casadi_copy(w22+6, 3, w25);
  /* #1077: @11 = @11' */
  /* #1078: {@41, NULL, @9} = horzsplit(@11) */
  w41 = w11[0];
  w9 = w11[2];
  /* #1079: @23 = (@23*@9) */
  w23 *= w9;
  /* #1080: @25 = @25' */
  /* #1081: {@9, NULL, @53} = horzsplit(@25) */
  w9 = w25[0];
  w53 = w25[2];
  /* #1082: @37 = (@37*@9) */
  w37 *= w9;
  /* #1083: @23 = (@23-@37) */
  w23 -= w37;
  /* #1084: @23 = (-@23) */
  w23 = (- w23 );
  /* #1085: @3 = (@3*@53) */
  w3 *= w53;
  /* #1086: @23 = (@23-@3) */
  w23 -= w3;
  /* #1087: @8 = (@8*@41) */
  w8 *= w41;
  /* #1088: @23 = (@23-@8) */
  w23 -= w8;
  /* #1089: (@0[22] = @23) */
  for (rr=w0+22, ss=(&w23); rr!=w0+23; rr+=1) *rr = *ss++;
  /* #1090: @67 = @0' */
  casadi_trans(w0,casadi_s7, w67, casadi_s6, iw);
  /* #1091: @23 = input[1][0] */
  w23 = arg[1] ? arg[1][0] : 0;
  /* #1092: @8 = input[1][1] */
  w8 = arg[1] ? arg[1][1] : 0;
  /* #1093: @41 = input[1][2] */
  w41 = arg[1] ? arg[1][2] : 0;
  /* #1094: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #1095: @53 = input[1][4] */
  w53 = arg[1] ? arg[1][4] : 0;
  /* #1096: @37 = input[1][5] */
  w37 = arg[1] ? arg[1][5] : 0;
  /* #1097: @9 = input[1][6] */
  w9 = arg[1] ? arg[1][6] : 0;
  /* #1098: @38 = input[1][7] */
  w38 = arg[1] ? arg[1][7] : 0;
  /* #1099: @24 = input[1][8] */
  w24 = arg[1] ? arg[1][8] : 0;
  /* #1100: @42 = input[1][9] */
  w42 = arg[1] ? arg[1][9] : 0;
  /* #1101: @50 = input[1][10] */
  w50 = arg[1] ? arg[1][10] : 0;
  /* #1102: @51 = input[1][11] */
  w51 = arg[1] ? arg[1][11] : 0;
  /* #1103: @15 = input[1][12] */
  w15 = arg[1] ? arg[1][12] : 0;
  /* #1104: @54 = input[1][13] */
  w54 = arg[1] ? arg[1][13] : 0;
  /* #1105: @68 = vertcat(@23, @8, @41, @3, @53, @37, @9, @38, @24, @42, @50, @51, @15, @54) */
  rr=w68;
  *rr++ = w23;
  *rr++ = w8;
  *rr++ = w41;
  *rr++ = w3;
  *rr++ = w53;
  *rr++ = w37;
  *rr++ = w9;
  *rr++ = w38;
  *rr++ = w24;
  *rr++ = w42;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w15;
  *rr++ = w54;
  /* #1106: @36 = mac(@67,@68,@36) */
  casadi_mtimes(w67, casadi_s6, w68, casadi_s8, w36, casadi_s3, w, 0);
  /* #1107: output[1][0] = @36 */
  casadi_copy(w36, 3, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 309;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[397];
  casadi_int iw[15];
  const casadi_real* arg[18] = {0};
  casadi_real* res[5] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many output arguments (%d, max 2)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s8, w+88);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+14, casadi_s8, w+88);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+28, casadi_s9, w+88);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+59, casadi_s3, w+88);
  --resc;
  res[0] = w+62;
  if (--resc>=0) res[1] = w+85;
  i = f(arg, res, iw, w+88, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s7, res[0]);
  if (res[1]) resv[1] = casadi_to_mex(casadi_s3, res[1]);
}
#endif

casadi_int main_f(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int iw[15];
  casadi_real w[397];
  const casadi_real* arg[18];
  casadi_real* res[5];
  arg[0] = w+0;
  arg[1] = w+14;
  arg[2] = w+28;
  arg[3] = w+59;
  res[0] = w+62;
  res[1] = w+85;
  a = w;
  for (j=0; j<62; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f(arg, res, iw, w+88, 0);
  if (flag) return flag;
  r = w+62;
  for (j=0; j<26; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[2];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f")==0) {
    mex_f(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f")==0) {
    return main_f(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
