/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) func_aerobat_aero_L_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_to_mex CASADI_PREFIX(to_mex)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s6[40] = {3, 14, 0, 1, 2, 3, 6, 9, 11, 14, 17, 20, 23, 23, 23, 23, 23, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s7[29] = {14, 3, 0, 8, 16, 23, 0, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 6, 7, 8, 9};
static const casadi_int casadi_s8[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s9[35] = {31, 1, 0, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {1., 0., 0.};

/* f:(i0[14],i1[14],i2[31],i3[3])->(o0[14x3,23nz],o1[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, w2, w3, *w4=w+29, *w5=w+38, w6, w7, w8, w9, *w10=w+51, *w11=w+54, *w12=w+57, *w13=w+60, *w14=w+69, w15, *w16=w+79, *w17=w+88, *w18=w+97, *w19=w+106, *w20=w+115, w21, *w22=w+125, *w23=w+128, *w24=w+137, w25, w26, *w27=w+148, *w28=w+157, w29, *w30=w+167, *w31=w+176, *w32=w+185, *w33=w+194, w34, w35, w36, w37, *w38=w+201, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, *w60=w+225, *w61=w+234, w62, w63, *w64=w+245, *w65=w+268;
  /* #0: @0 = zeros(14x3,23nz) */
  casadi_clear(w0, 23);
  /* #1: @1 = ones(3x1,1nz) */
  w1 = 1.;
  /* #2: {@2, NULL, NULL} = vertsplit(@1) */
  w2 = w1;
  /* #3: (@0[0] = @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #4: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #5: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #6: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #7: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #8: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #9: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #10: @8 = sin(@6) */
  w8 = sin( w6 );
  /* #11: @8 = (-@8) */
  w8 = (- w8 );
  /* #12: @9 = 0 */
  w9 = 0.;
  /* #13: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #14: @10 = @10' */
  /* #15: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #16: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #19: @11 = @11' */
  /* #20: @12 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w12);
  /* #21: @12 = @12' */
  /* #22: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #23: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #24: @7 = input[0][4] */
  w7 = arg[0] ? arg[0][4] : 0;
  /* #25: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #26: @9 = 0 */
  w9 = 0.;
  /* #27: @15 = sin(@7) */
  w15 = sin( w7 );
  /* #28: @10 = horzcat(@8, @9, @15) */
  rr=w10;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #29: @10 = @10' */
  /* #30: @11 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w11);
  /* #31: @11 = @11' */
  /* #32: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #33: @8 = (-@8) */
  w8 = (- w8 );
  /* #34: @9 = 0 */
  w9 = 0.;
  /* #35: @15 = cos(@7) */
  w15 = cos( w7 );
  /* #36: @12 = horzcat(@8, @9, @15) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w15;
  /* #37: @12 = @12' */
  /* #38: @16 = horzcat(@10, @11, @12) */
  rr=w16;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #39: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #40: @5 = mac(@14,@17,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #41: @14 = @5' */
  for (i=0, rr=w14, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #42: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #43: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #44: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #45: @10 = input[3][0] */
  casadi_copy(arg[3], 3, w10);
  /* #46: @11 = @10' */
  casadi_copy(w10, 3, w11);
  /* #47: @19 = mac(@1,@11,@19) */
  casadi_mtimes((&w1), casadi_s2, w11, casadi_s1, w19, casadi_s0, w, 0);
  /* #48: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #49: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #50: @11 = @11' */
  /* #51: @8 = 0 */
  w8 = 0.;
  /* #52: @9 = input[0][8] */
  w9 = arg[0] ? arg[0][8] : 0;
  /* #53: @15 = cos(@9) */
  w15 = cos( w9 );
  /* #54: @21 = sin(@9) */
  w21 = sin( w9 );
  /* #55: @21 = (-@21) */
  w21 = (- w21 );
  /* #56: @12 = horzcat(@8, @15, @21) */
  rr=w12;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w21;
  /* #57: @12 = @12' */
  /* #58: @8 = 0 */
  w8 = 0.;
  /* #59: @15 = sin(@9) */
  w15 = sin( w9 );
  /* #60: @21 = cos(@9) */
  w21 = cos( w9 );
  /* #61: @22 = horzcat(@8, @15, @21) */
  rr=w22;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w21;
  /* #62: @22 = @22' */
  /* #63: @23 = horzcat(@11, @12, @22) */
  rr=w23;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #64: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #65: @8 = input[0][9] */
  w8 = arg[0] ? arg[0][9] : 0;
  /* #66: @15 = cos(@8) */
  w15 = cos( w8 );
  /* #67: @21 = 0 */
  w21 = 0.;
  /* #68: @25 = (-@8) */
  w25 = (- w8 );
  /* #69: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #70: @11 = horzcat(@15, @21, @26) */
  rr=w11;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w26;
  /* #71: @11 = @11' */
  /* #72: @12 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w12);
  /* #73: @12 = @12' */
  /* #74: @25 = sin(@25) */
  w25 = sin( w25 );
  /* #75: @25 = (-@25) */
  w25 = (- w25 );
  /* #76: @15 = 0 */
  w15 = 0.;
  /* #77: @21 = cos(@8) */
  w21 = cos( w8 );
  /* #78: @22 = horzcat(@25, @15, @21) */
  rr=w22;
  *rr++ = w25;
  *rr++ = w15;
  *rr++ = w21;
  /* #79: @22 = @22' */
  /* #80: @27 = horzcat(@11, @12, @22) */
  rr=w27;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #81: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #82: @20 = mac(@24,@28,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #83: @24 = @20' */
  for (i=0, rr=w24, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #84: @18 = mac(@19,@24,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #85: @24 = zeros(3x3) */
  casadi_clear(w24, 9);
  /* #86: @25 = input[0][7] */
  w25 = arg[0] ? arg[0][7] : 0;
  /* #87: @15 = cos(@25) */
  w15 = cos( w25 );
  /* #88: @21 = (-@25) */
  w21 = (- w25 );
  /* #89: @26 = sin(@21) */
  w26 = sin( w21 );
  /* #90: @26 = (-@26) */
  w26 = (- w26 );
  /* #91: @29 = 0 */
  w29 = 0.;
  /* #92: @11 = horzcat(@15, @26, @29) */
  rr=w11;
  *rr++ = w15;
  *rr++ = w26;
  *rr++ = w29;
  /* #93: @11 = @11' */
  /* #94: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #95: @15 = cos(@25) */
  w15 = cos( w25 );
  /* #96: @26 = 0 */
  w26 = 0.;
  /* #97: @12 = horzcat(@21, @15, @26) */
  rr=w12;
  *rr++ = w21;
  *rr++ = w15;
  *rr++ = w26;
  /* #98: @12 = @12' */
  /* #99: @22 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w22);
  /* #100: @22 = @22' */
  /* #101: @28 = horzcat(@11, @12, @22) */
  rr=w28;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #102: @30 = @28' */
  for (i=0, rr=w30, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #103: @11 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w11);
  /* #104: @11 = @11' */
  /* #105: @21 = 0 */
  w21 = 0.;
  /* #106: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][6] : 0;
  /* #107: @26 = cos(@15) */
  w26 = cos( w15 );
  /* #108: @29 = sin(@15) */
  w29 = sin( w15 );
  /* #109: @29 = (-@29) */
  w29 = (- w29 );
  /* #110: @12 = horzcat(@21, @26, @29) */
  rr=w12;
  *rr++ = w21;
  *rr++ = w26;
  *rr++ = w29;
  /* #111: @12 = @12' */
  /* #112: @21 = 0 */
  w21 = 0.;
  /* #113: @26 = sin(@15) */
  w26 = sin( w15 );
  /* #114: @29 = cos(@15) */
  w29 = cos( w15 );
  /* #115: @22 = horzcat(@21, @26, @29) */
  rr=w22;
  *rr++ = w21;
  *rr++ = w26;
  *rr++ = w29;
  /* #116: @22 = @22' */
  /* #117: @31 = horzcat(@11, @12, @22) */
  rr=w31;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #118: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #119: @24 = mac(@30,@32,@24) */
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w30+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #120: @30 = @24' */
  for (i=0, rr=w30, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #121: @17 = mac(@18,@30,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #122: @30 = zeros(3x3) */
  casadi_clear(w30, 9);
  /* #123: @11 = input[2][4] */
  casadi_copy(arg[2] ? arg[2]+4 : 0, 3, w11);
  /* #124: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #125: @22 = input[2][5] */
  casadi_copy(arg[2] ? arg[2]+7 : 0, 3, w22);
  /* #126: @12 = mac(@24,@22,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #127: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #128: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #129: @30 = mac(@1,@12,@30) */
  casadi_mtimes((&w1), casadi_s2, w12, casadi_s1, w30, casadi_s0, w, 0);
  /* #130: @17 = (@17+@30) */
  for (i=0, rr=w17, cs=w30; i<9; ++i) (*rr++) += (*cs++);
  /* #131: @4 = mac(@14,@17,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #132: @14 = @4' */
  for (i=0, rr=w14, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #133: {NULL, @12, @33} = horzsplit(@14) */
  casadi_copy(w14+3, 3, w12);
  casadi_copy(w14+6, 3, w33);
  /* #134: @33 = @33' */
  /* #135: {NULL, @21, @26} = horzsplit(@33) */
  w21 = w33[1];
  w26 = w33[2];
  /* #136: @21 = (@3*@21) */
  w21  = (w3*w21);
  /* #137: @29 = sin(@2) */
  w29 = sin( w2 );
  /* #138: @26 = (@29*@26) */
  w26  = (w29*w26);
  /* #139: @21 = (@21-@26) */
  w21 -= w26;
  /* #140: @26 = cos(@2) */
  w26 = cos( w2 );
  /* #141: @12 = @12' */
  /* #142: {NULL, @34, @35} = horzsplit(@12) */
  w34 = w12[1];
  w35 = w12[2];
  /* #143: @35 = (@26*@35) */
  w35  = (w26*w35);
  /* #144: @21 = (@21-@35) */
  w21 -= w35;
  /* #145: @35 = sin(@2) */
  w35 = sin( w2 );
  /* #146: @34 = (@35*@34) */
  w34  = (w35*w34);
  /* #147: @21 = (@21-@34) */
  w21 -= w34;
  /* #148: (@0[1] = @21) */
  for (rr=w0+1, ss=(&w21); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #149: @21 = cos(@7) */
  w21 = cos( w7 );
  /* #150: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #151: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #152: @12 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w12);
  /* #153: @12 = @12' */
  /* #154: @34 = 0 */
  w34 = 0.;
  /* #155: @36 = cos(@2) */
  w36 = cos( w2 );
  /* #156: @37 = sin(@2) */
  w37 = sin( w2 );
  /* #157: @37 = (-@37) */
  w37 = (- w37 );
  /* #158: @33 = horzcat(@34, @36, @37) */
  rr=w33;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w37;
  /* #159: @33 = @33' */
  /* #160: @34 = 0 */
  w34 = 0.;
  /* #161: @36 = sin(@2) */
  w36 = sin( w2 );
  /* #162: @37 = cos(@2) */
  w37 = cos( w2 );
  /* #163: @38 = horzcat(@34, @36, @37) */
  rr=w38;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w37;
  /* #164: @38 = @38' */
  /* #165: @30 = horzcat(@12, @33, @38) */
  rr=w30;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #166: @4 = mac(@17,@30,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #167: @14 = mac(@13,@4,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #168: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #169: {@12, NULL, @33} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+6, 3, w33);
  /* #170: @33 = @33' */
  /* #171: {@34, NULL, @36} = horzsplit(@33) */
  w34 = w33[0];
  w36 = w33[2];
  /* #172: @34 = (@21*@34) */
  w34  = (w21*w34);
  /* #173: @34 = (-@34) */
  w34 = (- w34 );
  /* #174: @37 = sin(@7) */
  w37 = sin( w7 );
  /* #175: @36 = (@37*@36) */
  w36  = (w37*w36);
  /* #176: @34 = (@34-@36) */
  w34 -= w36;
  /* #177: @36 = cos(@7) */
  w36 = cos( w7 );
  /* #178: @12 = @12' */
  /* #179: {@39, NULL, @40} = horzsplit(@12) */
  w39 = w12[0];
  w40 = w12[2];
  /* #180: @40 = (@36*@40) */
  w40  = (w36*w40);
  /* #181: @34 = (@34+@40) */
  w34 += w40;
  /* #182: @40 = sin(@7) */
  w40 = sin( w7 );
  /* #183: @39 = (@40*@39) */
  w39  = (w40*w39);
  /* #184: @34 = (@34-@39) */
  w34 -= w39;
  /* #185: (@0[2] = @34) */
  for (rr=w0+2, ss=(&w34); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #186: @34 = cos(@6) */
  w34 = cos( w6 );
  /* #187: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #188: @17 = mac(@4,@16,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #189: @4 = @17' */
  for (i=0, rr=w4, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #190: {@12, @33, NULL} = horzsplit(@4) */
  casadi_copy(w4, 3, w12);
  casadi_copy(w4+3, 3, w33);
  /* #191: @33 = @33' */
  /* #192: {@39, @41, NULL} = horzsplit(@33) */
  w39 = w33[0];
  w41 = w33[1];
  /* #193: @39 = (@34*@39) */
  w39  = (w34*w39);
  /* #194: @42 = sin(@6) */
  w42 = sin( w6 );
  /* #195: @41 = (@42*@41) */
  w41  = (w42*w41);
  /* #196: @39 = (@39-@41) */
  w39 -= w41;
  /* #197: @41 = cos(@6) */
  w41 = cos( w6 );
  /* #198: @12 = @12' */
  /* #199: {@43, @44, NULL} = horzsplit(@12) */
  w43 = w12[0];
  w44 = w12[1];
  /* #200: @44 = (@41*@44) */
  w44  = (w41*w44);
  /* #201: @39 = (@39-@44) */
  w39 -= w44;
  /* #202: @44 = sin(@6) */
  w44 = sin( w6 );
  /* #203: @43 = (@44*@43) */
  w43  = (w44*w43);
  /* #204: @39 = (@39-@43) */
  w39 -= w43;
  /* #205: (@0[3] = @39) */
  for (rr=w0+3, ss=(&w39); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #206: @39 = cos(@15) */
  w39 = cos( w15 );
  /* #207: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #208: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #209: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #210: @32 = @30' */
  for (i=0, rr=w32, cs=w30; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #211: @14 = mac(@5,@32,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #212: @32 = @14' */
  for (i=0, rr=w32, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #213: @17 = mac(@32,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #214: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #215: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #216: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #217: @12 = mac(@18,@1,@12) */
  casadi_mtimes(w18, casadi_s0, (&w1), casadi_s2, w12, casadi_s3, w, 0);
  /* #218: @33 = @22' */
  casadi_copy(w22, 3, w33);
  /* #219: @32 = mac(@12,@33,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w33+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #220: @17 = (@17+@32) */
  for (i=0, rr=w17, cs=w32; i<9; ++i) (*rr++) += (*cs++);
  /* #221: @4 = mac(@28,@17,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #222: @32 = @4' */
  for (i=0, rr=w32, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #223: {NULL, @12, @33} = horzsplit(@32) */
  casadi_copy(w32+3, 3, w12);
  casadi_copy(w32+6, 3, w33);
  /* #224: @33 = @33' */
  /* #225: {NULL, @1, @43} = horzsplit(@33) */
  w1 = w33[1];
  w43 = w33[2];
  /* #226: @1 = (@39*@1) */
  w1  = (w39*w1);
  /* #227: @45 = sin(@15) */
  w45 = sin( w15 );
  /* #228: @43 = (@45*@43) */
  w43  = (w45*w43);
  /* #229: @1 = (@1-@43) */
  w1 -= w43;
  /* #230: @43 = cos(@15) */
  w43 = cos( w15 );
  /* #231: @12 = @12' */
  /* #232: {NULL, @46, @47} = horzsplit(@12) */
  w46 = w12[1];
  w47 = w12[2];
  /* #233: @47 = (@43*@47) */
  w47  = (w43*w47);
  /* #234: @1 = (@1-@47) */
  w1 -= w47;
  /* #235: @47 = sin(@15) */
  w47 = sin( w15 );
  /* #236: @46 = (@47*@46) */
  w46  = (w47*w46);
  /* #237: @1 = (@1-@46) */
  w1 -= w46;
  /* #238: (@0[4] = @1) */
  for (rr=w0+4, ss=(&w1); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #239: @1 = cos(@25) */
  w1 = cos( w25 );
  /* #240: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #241: @32 = mac(@17,@31,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #242: @17 = @32' */
  for (i=0, rr=w17, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: {@12, @33, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+3, 3, w33);
  /* #244: @33 = @33' */
  /* #245: {@46, @48, NULL} = horzsplit(@33) */
  w46 = w33[0];
  w48 = w33[1];
  /* #246: @46 = (@1*@46) */
  w46  = (w1*w46);
  /* #247: @49 = cos(@25) */
  w49 = cos( w25 );
  /* #248: @12 = @12' */
  /* #249: {@50, @51, NULL} = horzsplit(@12) */
  w50 = w12[0];
  w51 = w12[1];
  /* #250: @51 = (@49*@51) */
  w51  = (w49*w51);
  /* #251: @46 = (@46-@51) */
  w46 -= w51;
  /* #252: @46 = (-@46) */
  w46 = (- w46 );
  /* #253: @51 = sin(@25) */
  w51 = sin( w25 );
  /* #254: @48 = (@51*@48) */
  w48  = (w51*w48);
  /* #255: @46 = (@46-@48) */
  w46 -= w48;
  /* #256: @48 = sin(@25) */
  w48 = sin( w25 );
  /* #257: @50 = (@48*@50) */
  w50  = (w48*w50);
  /* #258: @46 = (@46-@50) */
  w46 -= w50;
  /* #259: (@0[5] = @46) */
  for (rr=w0+5, ss=(&w46); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #260: @46 = cos(@9) */
  w46 = cos( w9 );
  /* #261: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #262: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #263: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #264: @4 = mac(@14,@24,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #265: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #266: @32 = mac(@18,@19,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #267: @17 = mac(@32,@27,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #268: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #269: {NULL, @12, @33} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w33);
  /* #270: @33 = @33' */
  /* #271: {NULL, @50, @52} = horzsplit(@33) */
  w50 = w33[1];
  w52 = w33[2];
  /* #272: @50 = (@46*@50) */
  w50  = (w46*w50);
  /* #273: @53 = sin(@9) */
  w53 = sin( w9 );
  /* #274: @52 = (@53*@52) */
  w52  = (w53*w52);
  /* #275: @50 = (@50-@52) */
  w50 -= w52;
  /* #276: @52 = cos(@9) */
  w52 = cos( w9 );
  /* #277: @12 = @12' */
  /* #278: {NULL, @54, @55} = horzsplit(@12) */
  w54 = w12[1];
  w55 = w12[2];
  /* #279: @55 = (@52*@55) */
  w55  = (w52*w55);
  /* #280: @50 = (@50-@55) */
  w50 -= w55;
  /* #281: @55 = sin(@9) */
  w55 = sin( w9 );
  /* #282: @54 = (@55*@54) */
  w54  = (w55*w54);
  /* #283: @50 = (@50-@54) */
  w50 -= w54;
  /* #284: (@0[6] = @50) */
  for (rr=w0+6, ss=(&w50); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #285: @50 = cos(@8) */
  w50 = cos( w8 );
  /* #286: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #287: @18 = mac(@23,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #288: @32 = @18' */
  for (i=0, rr=w32, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #289: {@12, NULL, @33} = horzsplit(@32) */
  casadi_copy(w32, 3, w12);
  casadi_copy(w32+6, 3, w33);
  /* #290: @12 = @12' */
  /* #291: {@54, NULL, @56} = horzsplit(@12) */
  w54 = w12[0];
  w56 = w12[2];
  /* #292: @56 = (@50*@56) */
  w56  = (w50*w56);
  /* #293: @57 = cos(@8) */
  w57 = cos( w8 );
  /* #294: @33 = @33' */
  /* #295: {@58, NULL, @59} = horzsplit(@33) */
  w58 = w33[0];
  w59 = w33[2];
  /* #296: @58 = (@57*@58) */
  w58  = (w57*w58);
  /* #297: @56 = (@56-@58) */
  w56 -= w58;
  /* #298: @56 = (-@56) */
  w56 = (- w56 );
  /* #299: @58 = sin(@8) */
  w58 = sin( w8 );
  /* #300: @59 = (@58*@59) */
  w59  = (w58*w59);
  /* #301: @56 = (@56-@59) */
  w56 -= w59;
  /* #302: @59 = sin(@8) */
  w59 = sin( w8 );
  /* #303: @54 = (@59*@54) */
  w54  = (w59*w54);
  /* #304: @56 = (@56-@54) */
  w56 -= w54;
  /* #305: (@0[7] = @56) */
  for (rr=w0+7, ss=(&w56); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #306: @56 = ones(3x1,1nz) */
  w56 = 1.;
  /* #307: {NULL, @54, NULL} = vertsplit(@56) */
  w54 = w56;
  /* #308: (@0[8] = @54) */
  for (rr=w0+8, ss=(&w54); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #309: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #310: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #311: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #312: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #313: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #314: @33 = @10' */
  casadi_copy(w10, 3, w33);
  /* #315: @60 = mac(@56,@33,@60) */
  casadi_mtimes((&w56), casadi_s4, w33, casadi_s1, w60, casadi_s0, w, 0);
  /* #316: @61 = @20' */
  for (i=0, rr=w61, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #317: @19 = mac(@60,@61,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #318: @61 = @24' */
  for (i=0, rr=w61, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #319: @17 = mac(@19,@61,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #320: @61 = zeros(3x3) */
  casadi_clear(w61, 9);
  /* #321: @33 = @11' */
  casadi_copy(w11, 3, w33);
  /* #322: @61 = mac(@56,@33,@61) */
  casadi_mtimes((&w56), casadi_s4, w33, casadi_s1, w61, casadi_s0, w, 0);
  /* #323: @17 = (@17+@61) */
  for (i=0, rr=w17, cs=w61; i<9; ++i) (*rr++) += (*cs++);
  /* #324: @32 = mac(@18,@17,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #325: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #326: {NULL, @33, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w33);
  casadi_copy(w18+6, 3, w12);
  /* #327: @12 = @12' */
  /* #328: {NULL, @54, @62} = horzsplit(@12) */
  w54 = w12[1];
  w62 = w12[2];
  /* #329: @54 = (@3*@54) */
  w54  = (w3*w54);
  /* #330: @62 = (@29*@62) */
  w62  = (w29*w62);
  /* #331: @54 = (@54-@62) */
  w54 -= w62;
  /* #332: @33 = @33' */
  /* #333: {NULL, @62, @63} = horzsplit(@33) */
  w62 = w33[1];
  w63 = w33[2];
  /* #334: @63 = (@26*@63) */
  w63  = (w26*w63);
  /* #335: @54 = (@54-@63) */
  w54 -= w63;
  /* #336: @62 = (@35*@62) */
  w62  = (w35*w62);
  /* #337: @54 = (@54-@62) */
  w54 -= w62;
  /* #338: (@0[9] = @54) */
  for (rr=w0+9, ss=(&w54); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #339: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #340: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #341: @32 = mac(@17,@30,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #342: @18 = mac(@13,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #343: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #344: {@33, NULL, @12} = horzsplit(@17) */
  casadi_copy(w17, 3, w33);
  casadi_copy(w17+6, 3, w12);
  /* #345: @12 = @12' */
  /* #346: {@54, NULL, @62} = horzsplit(@12) */
  w54 = w12[0];
  w62 = w12[2];
  /* #347: @54 = (@21*@54) */
  w54  = (w21*w54);
  /* #348: @54 = (-@54) */
  w54 = (- w54 );
  /* #349: @62 = (@37*@62) */
  w62  = (w37*w62);
  /* #350: @54 = (@54-@62) */
  w54 -= w62;
  /* #351: @33 = @33' */
  /* #352: {@62, NULL, @63} = horzsplit(@33) */
  w62 = w33[0];
  w63 = w33[2];
  /* #353: @63 = (@36*@63) */
  w63  = (w36*w63);
  /* #354: @54 = (@54+@63) */
  w54 += w63;
  /* #355: @62 = (@40*@62) */
  w62  = (w40*w62);
  /* #356: @54 = (@54-@62) */
  w54 -= w62;
  /* #357: (@0[10] = @54) */
  for (rr=w0+10, ss=(&w54); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #358: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #359: @17 = mac(@32,@16,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #360: @32 = @17' */
  for (i=0, rr=w32, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #361: {@33, @12, NULL} = horzsplit(@32) */
  casadi_copy(w32, 3, w33);
  casadi_copy(w32+3, 3, w12);
  /* #362: @12 = @12' */
  /* #363: {@54, @62, NULL} = horzsplit(@12) */
  w54 = w12[0];
  w62 = w12[1];
  /* #364: @34 = (@34*@54) */
  w34 *= w54;
  /* #365: @42 = (@42*@62) */
  w42 *= w62;
  /* #366: @34 = (@34-@42) */
  w34 -= w42;
  /* #367: @33 = @33' */
  /* #368: {@42, @62, NULL} = horzsplit(@33) */
  w42 = w33[0];
  w62 = w33[1];
  /* #369: @41 = (@41*@62) */
  w41 *= w62;
  /* #370: @34 = (@34-@41) */
  w34 -= w41;
  /* #371: @44 = (@44*@42) */
  w44 *= w42;
  /* #372: @34 = (@34-@44) */
  w34 -= w44;
  /* #373: (@0[11] = @34) */
  for (rr=w0+11, ss=(&w34); rr!=w0+12; rr+=1) *rr = *ss++;
  /* #374: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #375: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #376: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #377: @17 = mac(@18,@19,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #378: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #379: @33 = zeros(3x1) */
  casadi_clear(w33, 3);
  /* #380: @19 = @14' */
  for (i=0, rr=w19, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #381: @33 = mac(@19,@56,@33) */
  casadi_mtimes(w19, casadi_s0, (&w56), casadi_s4, w33, casadi_s3, w, 0);
  /* #382: @12 = @22' */
  casadi_copy(w22, 3, w12);
  /* #383: @18 = mac(@33,@12,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w12+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #384: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #385: @32 = mac(@28,@17,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #386: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #387: {NULL, @33, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w33);
  casadi_copy(w18+6, 3, w12);
  /* #388: @12 = @12' */
  /* #389: {NULL, @56, @34} = horzsplit(@12) */
  w56 = w12[1];
  w34 = w12[2];
  /* #390: @56 = (@39*@56) */
  w56  = (w39*w56);
  /* #391: @34 = (@45*@34) */
  w34  = (w45*w34);
  /* #392: @56 = (@56-@34) */
  w56 -= w34;
  /* #393: @33 = @33' */
  /* #394: {NULL, @34, @44} = horzsplit(@33) */
  w34 = w33[1];
  w44 = w33[2];
  /* #395: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #396: @56 = (@56-@44) */
  w56 -= w44;
  /* #397: @34 = (@47*@34) */
  w34  = (w47*w34);
  /* #398: @56 = (@56-@34) */
  w56 -= w34;
  /* #399: (@0[12] = @56) */
  for (rr=w0+12, ss=(&w56); rr!=w0+13; rr+=1) *rr = *ss++;
  /* #400: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #401: @18 = mac(@17,@31,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #402: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #403: {@33, @12, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w33);
  casadi_copy(w17+3, 3, w12);
  /* #404: @12 = @12' */
  /* #405: {@56, @34, NULL} = horzsplit(@12) */
  w56 = w12[0];
  w34 = w12[1];
  /* #406: @56 = (@1*@56) */
  w56  = (w1*w56);
  /* #407: @33 = @33' */
  /* #408: {@44, @42, NULL} = horzsplit(@33) */
  w44 = w33[0];
  w42 = w33[1];
  /* #409: @42 = (@49*@42) */
  w42  = (w49*w42);
  /* #410: @56 = (@56-@42) */
  w56 -= w42;
  /* #411: @56 = (-@56) */
  w56 = (- w56 );
  /* #412: @34 = (@51*@34) */
  w34  = (w51*w34);
  /* #413: @56 = (@56-@34) */
  w56 -= w34;
  /* #414: @44 = (@48*@44) */
  w44  = (w48*w44);
  /* #415: @56 = (@56-@44) */
  w56 -= w44;
  /* #416: (@0[13] = @56) */
  for (rr=w0+13, ss=(&w56); rr!=w0+14; rr+=1) *rr = *ss++;
  /* #417: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #418: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #419: @32 = @4' */
  for (i=0, rr=w32, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #420: @18 = mac(@32,@60,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #421: @17 = mac(@18,@27,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #422: @32 = @17' */
  for (i=0, rr=w32, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #423: {NULL, @33, @12} = horzsplit(@32) */
  casadi_copy(w32+3, 3, w33);
  casadi_copy(w32+6, 3, w12);
  /* #424: @12 = @12' */
  /* #425: {NULL, @56, @44} = horzsplit(@12) */
  w56 = w12[1];
  w44 = w12[2];
  /* #426: @56 = (@46*@56) */
  w56  = (w46*w56);
  /* #427: @44 = (@53*@44) */
  w44  = (w53*w44);
  /* #428: @56 = (@56-@44) */
  w56 -= w44;
  /* #429: @33 = @33' */
  /* #430: {NULL, @44, @34} = horzsplit(@33) */
  w44 = w33[1];
  w34 = w33[2];
  /* #431: @34 = (@52*@34) */
  w34  = (w52*w34);
  /* #432: @56 = (@56-@34) */
  w56 -= w34;
  /* #433: @44 = (@55*@44) */
  w44  = (w55*w44);
  /* #434: @56 = (@56-@44) */
  w56 -= w44;
  /* #435: (@0[14] = @56) */
  for (rr=w0+14, ss=(&w56); rr!=w0+15; rr+=1) *rr = *ss++;
  /* #436: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #437: @32 = mac(@23,@18,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #438: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #439: {@33, NULL, @12} = horzsplit(@18) */
  casadi_copy(w18, 3, w33);
  casadi_copy(w18+6, 3, w12);
  /* #440: @33 = @33' */
  /* #441: {@56, NULL, @44} = horzsplit(@33) */
  w56 = w33[0];
  w44 = w33[2];
  /* #442: @44 = (@50*@44) */
  w44  = (w50*w44);
  /* #443: @12 = @12' */
  /* #444: {@34, NULL, @42} = horzsplit(@12) */
  w34 = w12[0];
  w42 = w12[2];
  /* #445: @34 = (@57*@34) */
  w34  = (w57*w34);
  /* #446: @44 = (@44-@34) */
  w44 -= w34;
  /* #447: @44 = (-@44) */
  w44 = (- w44 );
  /* #448: @42 = (@58*@42) */
  w42  = (w58*w42);
  /* #449: @44 = (@44-@42) */
  w44 -= w42;
  /* #450: @56 = (@59*@56) */
  w56  = (w59*w56);
  /* #451: @44 = (@44-@56) */
  w44 -= w56;
  /* #452: (@0[15] = @44) */
  for (rr=w0+15, ss=(&w44); rr!=w0+16; rr+=1) *rr = *ss++;
  /* #453: @44 = ones(3x1,1nz) */
  w44 = 1.;
  /* #454: {NULL, NULL, @56} = vertsplit(@44) */
  w56 = w44;
  /* #455: (@0[16] = @56) */
  for (rr=w0+16, ss=(&w56); rr!=w0+17; rr+=1) *rr = *ss++;
  /* #456: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #457: @32 = @5' */
  for (i=0, rr=w32, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #458: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #459: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #460: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #461: @12 = @10' */
  casadi_copy(w10, 3, w12);
  /* #462: @19 = mac(@44,@12,@19) */
  casadi_mtimes((&w44), casadi_s5, w12, casadi_s1, w19, casadi_s0, w, 0);
  /* #463: @61 = @20' */
  for (i=0, rr=w61, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #464: @60 = mac(@19,@61,@60) */
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #465: @61 = @24' */
  for (i=0, rr=w61, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #466: @17 = mac(@60,@61,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #467: @61 = zeros(3x3) */
  casadi_clear(w61, 9);
  /* #468: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #469: @61 = mac(@44,@12,@61) */
  casadi_mtimes((&w44), casadi_s5, w12, casadi_s1, w61, casadi_s0, w, 0);
  /* #470: @17 = (@17+@61) */
  for (i=0, rr=w17, cs=w61; i<9; ++i) (*rr++) += (*cs++);
  /* #471: @18 = mac(@32,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #472: @32 = @18' */
  for (i=0, rr=w32, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #473: {NULL, @12, @33} = horzsplit(@32) */
  casadi_copy(w32+3, 3, w12);
  casadi_copy(w32+6, 3, w33);
  /* #474: @33 = @33' */
  /* #475: {NULL, @56, @42} = horzsplit(@33) */
  w56 = w33[1];
  w42 = w33[2];
  /* #476: @3 = (@3*@56) */
  w3 *= w56;
  /* #477: @29 = (@29*@42) */
  w29 *= w42;
  /* #478: @3 = (@3-@29) */
  w3 -= w29;
  /* #479: @12 = @12' */
  /* #480: {NULL, @29, @42} = horzsplit(@12) */
  w29 = w12[1];
  w42 = w12[2];
  /* #481: @26 = (@26*@42) */
  w26 *= w42;
  /* #482: @3 = (@3-@26) */
  w3 -= w26;
  /* #483: @35 = (@35*@29) */
  w35 *= w29;
  /* #484: @3 = (@3-@35) */
  w3 -= w35;
  /* #485: (@0[17] = @3) */
  for (rr=w0+17, ss=(&w3); rr!=w0+18; rr+=1) *rr = *ss++;
  /* #486: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #487: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #488: @18 = mac(@17,@30,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #489: @32 = mac(@13,@18,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #490: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #491: {@12, NULL, @33} = horzsplit(@18) */
  casadi_copy(w18, 3, w12);
  casadi_copy(w18+6, 3, w33);
  /* #492: @33 = @33' */
  /* #493: {@3, NULL, @35} = horzsplit(@33) */
  w3 = w33[0];
  w35 = w33[2];
  /* #494: @21 = (@21*@3) */
  w21 *= w3;
  /* #495: @21 = (-@21) */
  w21 = (- w21 );
  /* #496: @37 = (@37*@35) */
  w37 *= w35;
  /* #497: @21 = (@21-@37) */
  w21 -= w37;
  /* #498: @12 = @12' */
  /* #499: {@37, NULL, @35} = horzsplit(@12) */
  w37 = w12[0];
  w35 = w12[2];
  /* #500: @36 = (@36*@35) */
  w36 *= w35;
  /* #501: @21 = (@21+@36) */
  w21 += w36;
  /* #502: @40 = (@40*@37) */
  w40 *= w37;
  /* #503: @21 = (@21-@40) */
  w21 -= w40;
  /* #504: (@0[18] = @21) */
  for (rr=w0+18, ss=(&w21); rr!=w0+19; rr+=1) *rr = *ss++;
  /* #505: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #506: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #507: @17 = @14' */
  for (i=0, rr=w17, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #508: @32 = mac(@17,@60,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #509: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #510: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #511: @60 = @14' */
  for (i=0, rr=w60, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #512: @12 = mac(@60,@44,@12) */
  casadi_mtimes(w60, casadi_s0, (&w44), casadi_s5, w12, casadi_s3, w, 0);
  /* #513: @33 = @22' */
  casadi_copy(w22, 3, w33);
  /* #514: @17 = mac(@12,@33,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w33+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #515: @32 = (@32+@17) */
  for (i=0, rr=w32, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #516: @18 = mac(@28,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #517: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #518: {NULL, @12, @33} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w12);
  casadi_copy(w17+6, 3, w33);
  /* #519: @33 = @33' */
  /* #520: {NULL, @44, @21} = horzsplit(@33) */
  w44 = w33[1];
  w21 = w33[2];
  /* #521: @39 = (@39*@44) */
  w39 *= w44;
  /* #522: @45 = (@45*@21) */
  w45 *= w21;
  /* #523: @39 = (@39-@45) */
  w39 -= w45;
  /* #524: @12 = @12' */
  /* #525: {NULL, @45, @21} = horzsplit(@12) */
  w45 = w12[1];
  w21 = w12[2];
  /* #526: @43 = (@43*@21) */
  w43 *= w21;
  /* #527: @39 = (@39-@43) */
  w39 -= w43;
  /* #528: @47 = (@47*@45) */
  w47 *= w45;
  /* #529: @39 = (@39-@47) */
  w39 -= w47;
  /* #530: (@0[19] = @39) */
  for (rr=w0+19, ss=(&w39); rr!=w0+20; rr+=1) *rr = *ss++;
  /* #531: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #532: @17 = mac(@32,@31,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #533: @32 = @17' */
  for (i=0, rr=w32, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #534: {@12, @33, NULL} = horzsplit(@32) */
  casadi_copy(w32, 3, w12);
  casadi_copy(w32+3, 3, w33);
  /* #535: @33 = @33' */
  /* #536: {@39, @47, NULL} = horzsplit(@33) */
  w39 = w33[0];
  w47 = w33[1];
  /* #537: @1 = (@1*@39) */
  w1 *= w39;
  /* #538: @12 = @12' */
  /* #539: {@39, @45, NULL} = horzsplit(@12) */
  w39 = w12[0];
  w45 = w12[1];
  /* #540: @49 = (@49*@45) */
  w49 *= w45;
  /* #541: @1 = (@1-@49) */
  w1 -= w49;
  /* #542: @1 = (-@1) */
  w1 = (- w1 );
  /* #543: @51 = (@51*@47) */
  w51 *= w47;
  /* #544: @1 = (@1-@51) */
  w1 -= w51;
  /* #545: @48 = (@48*@39) */
  w48 *= w39;
  /* #546: @1 = (@1-@48) */
  w1 -= w48;
  /* #547: (@0[20] = @1) */
  for (rr=w0+20, ss=(&w1); rr!=w0+21; rr+=1) *rr = *ss++;
  /* #548: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #549: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #550: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #551: @17 = mac(@18,@19,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #552: @32 = mac(@17,@27,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #553: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #554: {NULL, @12, @33} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w33);
  /* #555: @33 = @33' */
  /* #556: {NULL, @1, @48} = horzsplit(@33) */
  w1 = w33[1];
  w48 = w33[2];
  /* #557: @46 = (@46*@1) */
  w46 *= w1;
  /* #558: @53 = (@53*@48) */
  w53 *= w48;
  /* #559: @46 = (@46-@53) */
  w46 -= w53;
  /* #560: @12 = @12' */
  /* #561: {NULL, @53, @48} = horzsplit(@12) */
  w53 = w12[1];
  w48 = w12[2];
  /* #562: @52 = (@52*@48) */
  w52 *= w48;
  /* #563: @46 = (@46-@52) */
  w46 -= w52;
  /* #564: @55 = (@55*@53) */
  w55 *= w53;
  /* #565: @46 = (@46-@55) */
  w46 -= w55;
  /* #566: (@0[21] = @46) */
  for (rr=w0+21, ss=(&w46); rr!=w0+22; rr+=1) *rr = *ss++;
  /* #567: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #568: @18 = mac(@23,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #569: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #570: {@12, NULL, @33} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+6, 3, w33);
  /* #571: @12 = @12' */
  /* #572: {@46, NULL, @55} = horzsplit(@12) */
  w46 = w12[0];
  w55 = w12[2];
  /* #573: @50 = (@50*@55) */
  w50 *= w55;
  /* #574: @33 = @33' */
  /* #575: {@55, NULL, @53} = horzsplit(@33) */
  w55 = w33[0];
  w53 = w33[2];
  /* #576: @57 = (@57*@55) */
  w57 *= w55;
  /* #577: @50 = (@50-@57) */
  w50 -= w57;
  /* #578: @50 = (-@50) */
  w50 = (- w50 );
  /* #579: @58 = (@58*@53) */
  w58 *= w53;
  /* #580: @50 = (@50-@58) */
  w50 -= w58;
  /* #581: @59 = (@59*@46) */
  w59 *= w46;
  /* #582: @50 = (@50-@59) */
  w50 -= w59;
  /* #583: (@0[22] = @50) */
  for (rr=w0+22, ss=(&w50); rr!=w0+23; rr+=1) *rr = *ss++;
  /* #584: output[0][0] = @0 */
  casadi_copy(w0, 23, res[0]);
  /* #585: @33 = zeros(3x1) */
  casadi_clear(w33, 3);
  /* #586: @0 = zeros(14x3,23nz) */
  casadi_clear(w0, 23);
  /* #587: @50 = ones(3x1,1nz) */
  w50 = 1.;
  /* #588: {@59, NULL, NULL} = vertsplit(@50) */
  w59 = w50;
  /* #589: (@0[0] = @59) */
  for (rr=w0+0, ss=(&w59); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #590: @59 = cos(@2) */
  w59 = cos( w2 );
  /* #591: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #592: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #593: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #594: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #595: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #596: @12 = @10' */
  casadi_copy(w10, 3, w12);
  /* #597: @60 = mac(@50,@12,@60) */
  casadi_mtimes((&w50), casadi_s2, w12, casadi_s1, w60, casadi_s0, w, 0);
  /* #598: @61 = @20' */
  for (i=0, rr=w61, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #599: @19 = mac(@60,@61,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #600: @61 = @24' */
  for (i=0, rr=w61, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #601: @32 = mac(@19,@61,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #602: @61 = zeros(3x3) */
  casadi_clear(w61, 9);
  /* #603: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #604: @61 = mac(@50,@12,@61) */
  casadi_mtimes((&w50), casadi_s2, w12, casadi_s1, w61, casadi_s0, w, 0);
  /* #605: @32 = (@32+@61) */
  for (i=0, rr=w32, cs=w61; i<9; ++i) (*rr++) += (*cs++);
  /* #606: @17 = mac(@18,@32,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #607: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #608: {NULL, @12, @38} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w38);
  /* #609: @38 = @38' */
  /* #610: {NULL, @46, @58} = horzsplit(@38) */
  w46 = w38[1];
  w58 = w38[2];
  /* #611: @46 = (@59*@46) */
  w46  = (w59*w46);
  /* #612: @53 = sin(@2) */
  w53 = sin( w2 );
  /* #613: @58 = (@53*@58) */
  w58  = (w53*w58);
  /* #614: @46 = (@46-@58) */
  w46 -= w58;
  /* #615: @58 = cos(@2) */
  w58 = cos( w2 );
  /* #616: @12 = @12' */
  /* #617: {NULL, @57, @55} = horzsplit(@12) */
  w57 = w12[1];
  w55 = w12[2];
  /* #618: @55 = (@58*@55) */
  w55  = (w58*w55);
  /* #619: @46 = (@46-@55) */
  w46 -= w55;
  /* #620: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #621: @57 = (@2*@57) */
  w57  = (w2*w57);
  /* #622: @46 = (@46-@57) */
  w46 -= w57;
  /* #623: (@0[1] = @46) */
  for (rr=w0+1, ss=(&w46); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #624: @46 = cos(@7) */
  w46 = cos( w7 );
  /* #625: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #626: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #627: @17 = mac(@32,@30,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #628: @18 = mac(@13,@17,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #629: @32 = @18' */
  for (i=0, rr=w32, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #630: {@12, NULL, @38} = horzsplit(@32) */
  casadi_copy(w32, 3, w12);
  casadi_copy(w32+6, 3, w38);
  /* #631: @38 = @38' */
  /* #632: {@57, NULL, @55} = horzsplit(@38) */
  w57 = w38[0];
  w55 = w38[2];
  /* #633: @57 = (@46*@57) */
  w57  = (w46*w57);
  /* #634: @57 = (-@57) */
  w57 = (- w57 );
  /* #635: @52 = sin(@7) */
  w52 = sin( w7 );
  /* #636: @55 = (@52*@55) */
  w55  = (w52*w55);
  /* #637: @57 = (@57-@55) */
  w57 -= w55;
  /* #638: @55 = cos(@7) */
  w55 = cos( w7 );
  /* #639: @12 = @12' */
  /* #640: {@48, NULL, @1} = horzsplit(@12) */
  w48 = w12[0];
  w1 = w12[2];
  /* #641: @1 = (@55*@1) */
  w1  = (w55*w1);
  /* #642: @57 = (@57+@1) */
  w57 += w1;
  /* #643: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #644: @48 = (@7*@48) */
  w48  = (w7*w48);
  /* #645: @57 = (@57-@48) */
  w57 -= w48;
  /* #646: (@0[2] = @57) */
  for (rr=w0+2, ss=(&w57); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #647: @57 = cos(@6) */
  w57 = cos( w6 );
  /* #648: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #649: @32 = mac(@17,@16,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #650: @17 = @32' */
  for (i=0, rr=w17, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #651: {@12, @38, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w12);
  casadi_copy(w17+3, 3, w38);
  /* #652: @38 = @38' */
  /* #653: {@48, @1, NULL} = horzsplit(@38) */
  w48 = w38[0];
  w1 = w38[1];
  /* #654: @48 = (@57*@48) */
  w48  = (w57*w48);
  /* #655: @39 = sin(@6) */
  w39 = sin( w6 );
  /* #656: @1 = (@39*@1) */
  w1  = (w39*w1);
  /* #657: @48 = (@48-@1) */
  w48 -= w1;
  /* #658: @1 = cos(@6) */
  w1 = cos( w6 );
  /* #659: @12 = @12' */
  /* #660: {@51, @47, NULL} = horzsplit(@12) */
  w51 = w12[0];
  w47 = w12[1];
  /* #661: @47 = (@1*@47) */
  w47  = (w1*w47);
  /* #662: @48 = (@48-@47) */
  w48 -= w47;
  /* #663: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #664: @51 = (@6*@51) */
  w51  = (w6*w51);
  /* #665: @48 = (@48-@51) */
  w48 -= w51;
  /* #666: (@0[3] = @48) */
  for (rr=w0+3, ss=(&w48); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #667: @48 = cos(@15) */
  w48 = cos( w15 );
  /* #668: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #669: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #670: @18 = @14' */
  for (i=0, rr=w18, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #671: @32 = mac(@18,@19,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #672: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #673: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #674: @19 = @14' */
  for (i=0, rr=w19, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #675: @12 = mac(@19,@50,@12) */
  casadi_mtimes(w19, casadi_s0, (&w50), casadi_s2, w12, casadi_s3, w, 0);
  /* #676: @38 = @22' */
  casadi_copy(w22, 3, w38);
  /* #677: @18 = mac(@12,@38,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w38+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #678: @32 = (@32+@18) */
  for (i=0, rr=w32, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #679: @17 = mac(@28,@32,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #680: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #681: {NULL, @12, @38} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w12);
  casadi_copy(w18+6, 3, w38);
  /* #682: @38 = @38' */
  /* #683: {NULL, @50, @51} = horzsplit(@38) */
  w50 = w38[1];
  w51 = w38[2];
  /* #684: @50 = (@48*@50) */
  w50  = (w48*w50);
  /* #685: @47 = sin(@15) */
  w47 = sin( w15 );
  /* #686: @51 = (@47*@51) */
  w51  = (w47*w51);
  /* #687: @50 = (@50-@51) */
  w50 -= w51;
  /* #688: @51 = cos(@15) */
  w51 = cos( w15 );
  /* #689: @12 = @12' */
  /* #690: {NULL, @49, @45} = horzsplit(@12) */
  w49 = w12[1];
  w45 = w12[2];
  /* #691: @45 = (@51*@45) */
  w45  = (w51*w45);
  /* #692: @50 = (@50-@45) */
  w50 -= w45;
  /* #693: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #694: @49 = (@15*@49) */
  w49  = (w15*w49);
  /* #695: @50 = (@50-@49) */
  w50 -= w49;
  /* #696: (@0[4] = @50) */
  for (rr=w0+4, ss=(&w50); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #697: @50 = cos(@25) */
  w50 = cos( w25 );
  /* #698: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #699: @18 = mac(@32,@31,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #700: @32 = @18' */
  for (i=0, rr=w32, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #701: {@12, @38, NULL} = horzsplit(@32) */
  casadi_copy(w32, 3, w12);
  casadi_copy(w32+3, 3, w38);
  /* #702: @38 = @38' */
  /* #703: {@49, @45, NULL} = horzsplit(@38) */
  w49 = w38[0];
  w45 = w38[1];
  /* #704: @49 = (@50*@49) */
  w49  = (w50*w49);
  /* #705: @43 = cos(@25) */
  w43 = cos( w25 );
  /* #706: @12 = @12' */
  /* #707: {@21, @44, NULL} = horzsplit(@12) */
  w21 = w12[0];
  w44 = w12[1];
  /* #708: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #709: @49 = (@49-@44) */
  w49 -= w44;
  /* #710: @49 = (-@49) */
  w49 = (- w49 );
  /* #711: @44 = sin(@25) */
  w44 = sin( w25 );
  /* #712: @45 = (@44*@45) */
  w45  = (w44*w45);
  /* #713: @49 = (@49-@45) */
  w49 -= w45;
  /* #714: @25 = sin(@25) */
  w25 = sin( w25 );
  /* #715: @21 = (@25*@21) */
  w21  = (w25*w21);
  /* #716: @49 = (@49-@21) */
  w49 -= w21;
  /* #717: (@0[5] = @49) */
  for (rr=w0+5, ss=(&w49); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #718: @49 = cos(@9) */
  w49 = cos( w9 );
  /* #719: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #720: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #721: @17 = @4' */
  for (i=0, rr=w17, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #722: @18 = mac(@17,@60,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #723: @32 = mac(@18,@27,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #724: @17 = @32' */
  for (i=0, rr=w17, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #725: {NULL, @12, @38} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w12);
  casadi_copy(w17+6, 3, w38);
  /* #726: @38 = @38' */
  /* #727: {NULL, @21, @45} = horzsplit(@38) */
  w21 = w38[1];
  w45 = w38[2];
  /* #728: @21 = (@49*@21) */
  w21  = (w49*w21);
  /* #729: @40 = sin(@9) */
  w40 = sin( w9 );
  /* #730: @45 = (@40*@45) */
  w45  = (w40*w45);
  /* #731: @21 = (@21-@45) */
  w21 -= w45;
  /* #732: @45 = cos(@9) */
  w45 = cos( w9 );
  /* #733: @12 = @12' */
  /* #734: {NULL, @37, @36} = horzsplit(@12) */
  w37 = w12[1];
  w36 = w12[2];
  /* #735: @36 = (@45*@36) */
  w36  = (w45*w36);
  /* #736: @21 = (@21-@36) */
  w21 -= w36;
  /* #737: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #738: @37 = (@9*@37) */
  w37  = (w9*w37);
  /* #739: @21 = (@21-@37) */
  w21 -= w37;
  /* #740: (@0[6] = @21) */
  for (rr=w0+6, ss=(&w21); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #741: @21 = cos(@8) */
  w21 = cos( w8 );
  /* #742: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #743: @17 = mac(@23,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #744: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #745: {@12, NULL, @38} = horzsplit(@18) */
  casadi_copy(w18, 3, w12);
  casadi_copy(w18+6, 3, w38);
  /* #746: @12 = @12' */
  /* #747: {@37, NULL, @36} = horzsplit(@12) */
  w37 = w12[0];
  w36 = w12[2];
  /* #748: @36 = (@21*@36) */
  w36  = (w21*w36);
  /* #749: @35 = cos(@8) */
  w35 = cos( w8 );
  /* #750: @38 = @38' */
  /* #751: {@3, NULL, @29} = horzsplit(@38) */
  w3 = w38[0];
  w29 = w38[2];
  /* #752: @3 = (@35*@3) */
  w3  = (w35*w3);
  /* #753: @36 = (@36-@3) */
  w36 -= w3;
  /* #754: @36 = (-@36) */
  w36 = (- w36 );
  /* #755: @3 = sin(@8) */
  w3 = sin( w8 );
  /* #756: @29 = (@3*@29) */
  w29  = (w3*w29);
  /* #757: @36 = (@36-@29) */
  w36 -= w29;
  /* #758: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #759: @37 = (@8*@37) */
  w37  = (w8*w37);
  /* #760: @36 = (@36-@37) */
  w36 -= w37;
  /* #761: (@0[7] = @36) */
  for (rr=w0+7, ss=(&w36); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #762: @36 = ones(3x1,1nz) */
  w36 = 1.;
  /* #763: {NULL, @37, NULL} = vertsplit(@36) */
  w37 = w36;
  /* #764: (@0[8] = @37) */
  for (rr=w0+8, ss=(&w37); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #765: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #766: @17 = @5' */
  for (i=0, rr=w17, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #767: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #768: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #769: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #770: @38 = @10' */
  casadi_copy(w10, 3, w38);
  /* #771: @19 = mac(@36,@38,@19) */
  casadi_mtimes((&w36), casadi_s4, w38, casadi_s1, w19, casadi_s0, w, 0);
  /* #772: @61 = @20' */
  for (i=0, rr=w61, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #773: @60 = mac(@19,@61,@60) */
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #774: @61 = @24' */
  for (i=0, rr=w61, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #775: @32 = mac(@60,@61,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #776: @61 = zeros(3x3) */
  casadi_clear(w61, 9);
  /* #777: @38 = @11' */
  casadi_copy(w11, 3, w38);
  /* #778: @61 = mac(@36,@38,@61) */
  casadi_mtimes((&w36), casadi_s4, w38, casadi_s1, w61, casadi_s0, w, 0);
  /* #779: @32 = (@32+@61) */
  for (i=0, rr=w32, cs=w61; i<9; ++i) (*rr++) += (*cs++);
  /* #780: @18 = mac(@17,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #781: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #782: {NULL, @38, @12} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w38);
  casadi_copy(w17+6, 3, w12);
  /* #783: @12 = @12' */
  /* #784: {NULL, @37, @29} = horzsplit(@12) */
  w37 = w12[1];
  w29 = w12[2];
  /* #785: @37 = (@59*@37) */
  w37  = (w59*w37);
  /* #786: @29 = (@53*@29) */
  w29  = (w53*w29);
  /* #787: @37 = (@37-@29) */
  w37 -= w29;
  /* #788: @38 = @38' */
  /* #789: {NULL, @29, @26} = horzsplit(@38) */
  w29 = w38[1];
  w26 = w38[2];
  /* #790: @26 = (@58*@26) */
  w26  = (w58*w26);
  /* #791: @37 = (@37-@26) */
  w37 -= w26;
  /* #792: @29 = (@2*@29) */
  w29  = (w2*w29);
  /* #793: @37 = (@37-@29) */
  w37 -= w29;
  /* #794: (@0[9] = @37) */
  for (rr=w0+9, ss=(&w37); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #795: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #796: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #797: @18 = mac(@32,@30,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #798: @17 = mac(@13,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #799: @32 = @17' */
  for (i=0, rr=w32, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #800: {@38, NULL, @12} = horzsplit(@32) */
  casadi_copy(w32, 3, w38);
  casadi_copy(w32+6, 3, w12);
  /* #801: @12 = @12' */
  /* #802: {@37, NULL, @29} = horzsplit(@12) */
  w37 = w12[0];
  w29 = w12[2];
  /* #803: @37 = (@46*@37) */
  w37  = (w46*w37);
  /* #804: @37 = (-@37) */
  w37 = (- w37 );
  /* #805: @29 = (@52*@29) */
  w29  = (w52*w29);
  /* #806: @37 = (@37-@29) */
  w37 -= w29;
  /* #807: @38 = @38' */
  /* #808: {@29, NULL, @26} = horzsplit(@38) */
  w29 = w38[0];
  w26 = w38[2];
  /* #809: @26 = (@55*@26) */
  w26  = (w55*w26);
  /* #810: @37 = (@37+@26) */
  w37 += w26;
  /* #811: @29 = (@7*@29) */
  w29  = (w7*w29);
  /* #812: @37 = (@37-@29) */
  w37 -= w29;
  /* #813: (@0[10] = @37) */
  for (rr=w0+10, ss=(&w37); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #814: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #815: @32 = mac(@18,@16,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #816: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #817: {@38, @12, NULL} = horzsplit(@18) */
  casadi_copy(w18, 3, w38);
  casadi_copy(w18+3, 3, w12);
  /* #818: @12 = @12' */
  /* #819: {@37, @29, NULL} = horzsplit(@12) */
  w37 = w12[0];
  w29 = w12[1];
  /* #820: @57 = (@57*@37) */
  w57 *= w37;
  /* #821: @39 = (@39*@29) */
  w39 *= w29;
  /* #822: @57 = (@57-@39) */
  w57 -= w39;
  /* #823: @38 = @38' */
  /* #824: {@39, @29, NULL} = horzsplit(@38) */
  w39 = w38[0];
  w29 = w38[1];
  /* #825: @1 = (@1*@29) */
  w1 *= w29;
  /* #826: @57 = (@57-@1) */
  w57 -= w1;
  /* #827: @6 = (@6*@39) */
  w6 *= w39;
  /* #828: @57 = (@57-@6) */
  w57 -= w6;
  /* #829: (@0[11] = @57) */
  for (rr=w0+11, ss=(&w57); rr!=w0+12; rr+=1) *rr = *ss++;
  /* #830: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #831: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #832: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #833: @32 = mac(@16,@60,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #834: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #835: @38 = zeros(3x1) */
  casadi_clear(w38, 3);
  /* #836: @60 = @14' */
  for (i=0, rr=w60, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #837: @38 = mac(@60,@36,@38) */
  casadi_mtimes(w60, casadi_s0, (&w36), casadi_s4, w38, casadi_s3, w, 0);
  /* #838: @12 = @22' */
  casadi_copy(w22, 3, w12);
  /* #839: @16 = mac(@38,@12,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w38+j, tt=w12+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #840: @32 = (@32+@16) */
  for (i=0, rr=w32, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #841: @18 = mac(@28,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #842: @16 = @18' */
  for (i=0, rr=w16, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #843: {NULL, @38, @12} = horzsplit(@16) */
  casadi_copy(w16+3, 3, w38);
  casadi_copy(w16+6, 3, w12);
  /* #844: @12 = @12' */
  /* #845: {NULL, @36, @57} = horzsplit(@12) */
  w36 = w12[1];
  w57 = w12[2];
  /* #846: @36 = (@48*@36) */
  w36  = (w48*w36);
  /* #847: @57 = (@47*@57) */
  w57  = (w47*w57);
  /* #848: @36 = (@36-@57) */
  w36 -= w57;
  /* #849: @38 = @38' */
  /* #850: {NULL, @57, @6} = horzsplit(@38) */
  w57 = w38[1];
  w6 = w38[2];
  /* #851: @6 = (@51*@6) */
  w6  = (w51*w6);
  /* #852: @36 = (@36-@6) */
  w36 -= w6;
  /* #853: @57 = (@15*@57) */
  w57  = (w15*w57);
  /* #854: @36 = (@36-@57) */
  w36 -= w57;
  /* #855: (@0[12] = @36) */
  for (rr=w0+12, ss=(&w36); rr!=w0+13; rr+=1) *rr = *ss++;
  /* #856: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #857: @16 = mac(@32,@31,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #858: @32 = @16' */
  for (i=0, rr=w32, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #859: {@38, @12, NULL} = horzsplit(@32) */
  casadi_copy(w32, 3, w38);
  casadi_copy(w32+3, 3, w12);
  /* #860: @12 = @12' */
  /* #861: {@36, @57, NULL} = horzsplit(@12) */
  w36 = w12[0];
  w57 = w12[1];
  /* #862: @36 = (@50*@36) */
  w36  = (w50*w36);
  /* #863: @38 = @38' */
  /* #864: {@6, @39, NULL} = horzsplit(@38) */
  w6 = w38[0];
  w39 = w38[1];
  /* #865: @39 = (@43*@39) */
  w39  = (w43*w39);
  /* #866: @36 = (@36-@39) */
  w36 -= w39;
  /* #867: @36 = (-@36) */
  w36 = (- w36 );
  /* #868: @57 = (@44*@57) */
  w57  = (w44*w57);
  /* #869: @36 = (@36-@57) */
  w36 -= w57;
  /* #870: @6 = (@25*@6) */
  w6  = (w25*w6);
  /* #871: @36 = (@36-@6) */
  w36 -= w6;
  /* #872: (@0[13] = @36) */
  for (rr=w0+13, ss=(&w36); rr!=w0+14; rr+=1) *rr = *ss++;
  /* #873: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #874: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #875: @18 = @4' */
  for (i=0, rr=w18, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #876: @16 = mac(@18,@19,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #877: @32 = mac(@16,@27,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #878: @18 = @32' */
  for (i=0, rr=w18, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #879: {NULL, @38, @12} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w38);
  casadi_copy(w18+6, 3, w12);
  /* #880: @12 = @12' */
  /* #881: {NULL, @36, @6} = horzsplit(@12) */
  w36 = w12[1];
  w6 = w12[2];
  /* #882: @36 = (@49*@36) */
  w36  = (w49*w36);
  /* #883: @6 = (@40*@6) */
  w6  = (w40*w6);
  /* #884: @36 = (@36-@6) */
  w36 -= w6;
  /* #885: @38 = @38' */
  /* #886: {NULL, @6, @57} = horzsplit(@38) */
  w6 = w38[1];
  w57 = w38[2];
  /* #887: @57 = (@45*@57) */
  w57  = (w45*w57);
  /* #888: @36 = (@36-@57) */
  w36 -= w57;
  /* #889: @6 = (@9*@6) */
  w6  = (w9*w6);
  /* #890: @36 = (@36-@6) */
  w36 -= w6;
  /* #891: (@0[14] = @36) */
  for (rr=w0+14, ss=(&w36); rr!=w0+15; rr+=1) *rr = *ss++;
  /* #892: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #893: @18 = mac(@23,@16,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #894: @16 = @18' */
  for (i=0, rr=w16, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #895: {@38, NULL, @12} = horzsplit(@16) */
  casadi_copy(w16, 3, w38);
  casadi_copy(w16+6, 3, w12);
  /* #896: @38 = @38' */
  /* #897: {@36, NULL, @6} = horzsplit(@38) */
  w36 = w38[0];
  w6 = w38[2];
  /* #898: @6 = (@21*@6) */
  w6  = (w21*w6);
  /* #899: @12 = @12' */
  /* #900: {@57, NULL, @39} = horzsplit(@12) */
  w57 = w12[0];
  w39 = w12[2];
  /* #901: @57 = (@35*@57) */
  w57  = (w35*w57);
  /* #902: @6 = (@6-@57) */
  w6 -= w57;
  /* #903: @6 = (-@6) */
  w6 = (- w6 );
  /* #904: @39 = (@3*@39) */
  w39  = (w3*w39);
  /* #905: @6 = (@6-@39) */
  w6 -= w39;
  /* #906: @36 = (@8*@36) */
  w36  = (w8*w36);
  /* #907: @6 = (@6-@36) */
  w6 -= w36;
  /* #908: (@0[15] = @6) */
  for (rr=w0+15, ss=(&w6); rr!=w0+16; rr+=1) *rr = *ss++;
  /* #909: @6 = ones(3x1,1nz) */
  w6 = 1.;
  /* #910: {NULL, NULL, @36} = vertsplit(@6) */
  w36 = w6;
  /* #911: (@0[16] = @36) */
  for (rr=w0+16, ss=(&w36); rr!=w0+17; rr+=1) *rr = *ss++;
  /* #912: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #913: @18 = @5' */
  for (i=0, rr=w18, cs=w5; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #914: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #915: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #916: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #917: @10 = @10' */
  /* #918: @19 = mac(@6,@10,@19) */
  casadi_mtimes((&w6), casadi_s5, w10, casadi_s1, w19, casadi_s0, w, 0);
  /* #919: @60 = @20' */
  for (i=0, rr=w60, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #920: @32 = mac(@19,@60,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #921: @60 = @24' */
  for (i=0, rr=w60, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #922: @5 = mac(@32,@60,@5) */
  for (i=0, rr=w5; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w60+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #923: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #924: @11 = @11' */
  /* #925: @60 = mac(@6,@11,@60) */
  casadi_mtimes((&w6), casadi_s5, w11, casadi_s1, w60, casadi_s0, w, 0);
  /* #926: @5 = (@5+@60) */
  for (i=0, rr=w5, cs=w60; i<9; ++i) (*rr++) += (*cs++);
  /* #927: @16 = mac(@18,@5,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #928: @18 = @16' */
  for (i=0, rr=w18, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #929: {NULL, @11, @10} = horzsplit(@18) */
  casadi_copy(w18+3, 3, w11);
  casadi_copy(w18+6, 3, w10);
  /* #930: @10 = @10' */
  /* #931: {NULL, @36, @39} = horzsplit(@10) */
  w36 = w10[1];
  w39 = w10[2];
  /* #932: @59 = (@59*@36) */
  w59 *= w36;
  /* #933: @53 = (@53*@39) */
  w53 *= w39;
  /* #934: @59 = (@59-@53) */
  w59 -= w53;
  /* #935: @11 = @11' */
  /* #936: {NULL, @53, @39} = horzsplit(@11) */
  w53 = w11[1];
  w39 = w11[2];
  /* #937: @58 = (@58*@39) */
  w58 *= w39;
  /* #938: @59 = (@59-@58) */
  w59 -= w58;
  /* #939: @2 = (@2*@53) */
  w2 *= w53;
  /* #940: @59 = (@59-@2) */
  w59 -= w2;
  /* #941: (@0[17] = @59) */
  for (rr=w0+17, ss=(&w59); rr!=w0+18; rr+=1) *rr = *ss++;
  /* #942: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #943: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #944: @16 = mac(@5,@30,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #945: @18 = mac(@13,@16,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #946: @13 = @18' */
  for (i=0, rr=w13, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #947: {@11, NULL, @10} = horzsplit(@13) */
  casadi_copy(w13, 3, w11);
  casadi_copy(w13+6, 3, w10);
  /* #948: @10 = @10' */
  /* #949: {@59, NULL, @2} = horzsplit(@10) */
  w59 = w10[0];
  w2 = w10[2];
  /* #950: @46 = (@46*@59) */
  w46 *= w59;
  /* #951: @46 = (-@46) */
  w46 = (- w46 );
  /* #952: @52 = (@52*@2) */
  w52 *= w2;
  /* #953: @46 = (@46-@52) */
  w46 -= w52;
  /* #954: @11 = @11' */
  /* #955: {@52, NULL, @2} = horzsplit(@11) */
  w52 = w11[0];
  w2 = w11[2];
  /* #956: @55 = (@55*@2) */
  w55 *= w2;
  /* #957: @46 = (@46+@55) */
  w46 += w55;
  /* #958: @7 = (@7*@52) */
  w7 *= w52;
  /* #959: @46 = (@46-@7) */
  w46 -= w7;
  /* #960: (@0[18] = @46) */
  for (rr=w0+18, ss=(&w46); rr!=w0+19; rr+=1) *rr = *ss++;
  /* #961: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #962: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #963: @16 = @14' */
  for (i=0, rr=w16, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #964: @18 = mac(@16,@32,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #965: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #966: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #967: @32 = @14' */
  for (i=0, rr=w32, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #968: @11 = mac(@32,@6,@11) */
  casadi_mtimes(w32, casadi_s0, (&w6), casadi_s5, w11, casadi_s3, w, 0);
  /* #969: @22 = @22' */
  /* #970: @16 = mac(@11,@22,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w22+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #971: @18 = (@18+@16) */
  for (i=0, rr=w18, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #972: @13 = mac(@28,@18,@13) */
  for (i=0, rr=w13; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #973: @28 = @13' */
  for (i=0, rr=w28, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #974: {NULL, @11, @22} = horzsplit(@28) */
  casadi_copy(w28+3, 3, w11);
  casadi_copy(w28+6, 3, w22);
  /* #975: @22 = @22' */
  /* #976: {NULL, @6, @46} = horzsplit(@22) */
  w6 = w22[1];
  w46 = w22[2];
  /* #977: @48 = (@48*@6) */
  w48 *= w6;
  /* #978: @47 = (@47*@46) */
  w47 *= w46;
  /* #979: @48 = (@48-@47) */
  w48 -= w47;
  /* #980: @11 = @11' */
  /* #981: {NULL, @47, @46} = horzsplit(@11) */
  w47 = w11[1];
  w46 = w11[2];
  /* #982: @51 = (@51*@46) */
  w51 *= w46;
  /* #983: @48 = (@48-@51) */
  w48 -= w51;
  /* #984: @15 = (@15*@47) */
  w15 *= w47;
  /* #985: @48 = (@48-@15) */
  w48 -= w15;
  /* #986: (@0[19] = @48) */
  for (rr=w0+19, ss=(&w48); rr!=w0+20; rr+=1) *rr = *ss++;
  /* #987: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #988: @28 = mac(@18,@31,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #989: @18 = @28' */
  for (i=0, rr=w18, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #990: {@11, @22, NULL} = horzsplit(@18) */
  casadi_copy(w18, 3, w11);
  casadi_copy(w18+3, 3, w22);
  /* #991: @22 = @22' */
  /* #992: {@48, @15, NULL} = horzsplit(@22) */
  w48 = w22[0];
  w15 = w22[1];
  /* #993: @50 = (@50*@48) */
  w50 *= w48;
  /* #994: @11 = @11' */
  /* #995: {@48, @47, NULL} = horzsplit(@11) */
  w48 = w11[0];
  w47 = w11[1];
  /* #996: @43 = (@43*@47) */
  w43 *= w47;
  /* #997: @50 = (@50-@43) */
  w50 -= w43;
  /* #998: @50 = (-@50) */
  w50 = (- w50 );
  /* #999: @44 = (@44*@15) */
  w44 *= w15;
  /* #1000: @50 = (@50-@44) */
  w50 -= w44;
  /* #1001: @25 = (@25*@48) */
  w25 *= w48;
  /* #1002: @50 = (@50-@25) */
  w50 -= w25;
  /* #1003: (@0[20] = @50) */
  for (rr=w0+20, ss=(&w50); rr!=w0+21; rr+=1) *rr = *ss++;
  /* #1004: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #1005: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #1006: @31 = @4' */
  for (i=0, rr=w31, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1007: @28 = mac(@31,@19,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w31+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1008: @18 = mac(@28,@27,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1009: @27 = @18' */
  for (i=0, rr=w27, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1010: {NULL, @11, @22} = horzsplit(@27) */
  casadi_copy(w27+3, 3, w11);
  casadi_copy(w27+6, 3, w22);
  /* #1011: @22 = @22' */
  /* #1012: {NULL, @50, @25} = horzsplit(@22) */
  w50 = w22[1];
  w25 = w22[2];
  /* #1013: @49 = (@49*@50) */
  w49 *= w50;
  /* #1014: @40 = (@40*@25) */
  w40 *= w25;
  /* #1015: @49 = (@49-@40) */
  w49 -= w40;
  /* #1016: @11 = @11' */
  /* #1017: {NULL, @40, @25} = horzsplit(@11) */
  w40 = w11[1];
  w25 = w11[2];
  /* #1018: @45 = (@45*@25) */
  w45 *= w25;
  /* #1019: @49 = (@49-@45) */
  w49 -= w45;
  /* #1020: @9 = (@9*@40) */
  w9 *= w40;
  /* #1021: @49 = (@49-@9) */
  w49 -= w9;
  /* #1022: (@0[21] = @49) */
  for (rr=w0+21, ss=(&w49); rr!=w0+22; rr+=1) *rr = *ss++;
  /* #1023: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #1024: @27 = mac(@23,@28,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #1025: @23 = @27' */
  for (i=0, rr=w23, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #1026: {@11, NULL, @22} = horzsplit(@23) */
  casadi_copy(w23, 3, w11);
  casadi_copy(w23+6, 3, w22);
  /* #1027: @11 = @11' */
  /* #1028: {@49, NULL, @9} = horzsplit(@11) */
  w49 = w11[0];
  w9 = w11[2];
  /* #1029: @21 = (@21*@9) */
  w21 *= w9;
  /* #1030: @22 = @22' */
  /* #1031: {@9, NULL, @40} = horzsplit(@22) */
  w9 = w22[0];
  w40 = w22[2];
  /* #1032: @35 = (@35*@9) */
  w35 *= w9;
  /* #1033: @21 = (@21-@35) */
  w21 -= w35;
  /* #1034: @21 = (-@21) */
  w21 = (- w21 );
  /* #1035: @3 = (@3*@40) */
  w3 *= w40;
  /* #1036: @21 = (@21-@3) */
  w21 -= w3;
  /* #1037: @8 = (@8*@49) */
  w8 *= w49;
  /* #1038: @21 = (@21-@8) */
  w21 -= w8;
  /* #1039: (@0[22] = @21) */
  for (rr=w0+22, ss=(&w21); rr!=w0+23; rr+=1) *rr = *ss++;
  /* #1040: @64 = @0' */
  casadi_trans(w0,casadi_s7, w64, casadi_s6, iw);
  /* #1041: @21 = input[1][0] */
  w21 = arg[1] ? arg[1][0] : 0;
  /* #1042: @8 = input[1][1] */
  w8 = arg[1] ? arg[1][1] : 0;
  /* #1043: @49 = input[1][2] */
  w49 = arg[1] ? arg[1][2] : 0;
  /* #1044: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #1045: @40 = input[1][4] */
  w40 = arg[1] ? arg[1][4] : 0;
  /* #1046: @35 = input[1][5] */
  w35 = arg[1] ? arg[1][5] : 0;
  /* #1047: @9 = input[1][6] */
  w9 = arg[1] ? arg[1][6] : 0;
  /* #1048: @45 = input[1][7] */
  w45 = arg[1] ? arg[1][7] : 0;
  /* #1049: @25 = input[1][8] */
  w25 = arg[1] ? arg[1][8] : 0;
  /* #1050: @50 = input[1][9] */
  w50 = arg[1] ? arg[1][9] : 0;
  /* #1051: @48 = input[1][10] */
  w48 = arg[1] ? arg[1][10] : 0;
  /* #1052: @44 = input[1][11] */
  w44 = arg[1] ? arg[1][11] : 0;
  /* #1053: @15 = input[1][12] */
  w15 = arg[1] ? arg[1][12] : 0;
  /* #1054: @43 = input[1][13] */
  w43 = arg[1] ? arg[1][13] : 0;
  /* #1055: @65 = vertcat(@21, @8, @49, @3, @40, @35, @9, @45, @25, @50, @48, @44, @15, @43) */
  rr=w65;
  *rr++ = w21;
  *rr++ = w8;
  *rr++ = w49;
  *rr++ = w3;
  *rr++ = w40;
  *rr++ = w35;
  *rr++ = w9;
  *rr++ = w45;
  *rr++ = w25;
  *rr++ = w50;
  *rr++ = w48;
  *rr++ = w44;
  *rr++ = w15;
  *rr++ = w43;
  /* #1056: @33 = mac(@64,@65,@33) */
  casadi_mtimes(w64, casadi_s6, w65, casadi_s8, w33, casadi_s3, w, 0);
  /* #1057: output[1][0] = @33 */
  casadi_copy(w33, 3, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 282;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[370];
  casadi_int iw[15];
  const casadi_real* arg[18] = {0};
  casadi_real* res[5] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many output arguments (%d, max 2)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s8, w+88);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+14, casadi_s8, w+88);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+28, casadi_s9, w+88);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+59, casadi_s3, w+88);
  --resc;
  res[0] = w+62;
  if (--resc>=0) res[1] = w+85;
  i = f(arg, res, iw, w+88, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s7, res[0]);
  if (res[1]) resv[1] = casadi_to_mex(casadi_s3, res[1]);
}
#endif

casadi_int main_f(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int iw[15];
  casadi_real w[370];
  const casadi_real* arg[18];
  casadi_real* res[5];
  arg[0] = w+0;
  arg[1] = w+14;
  arg[2] = w+28;
  arg[3] = w+59;
  res[0] = w+62;
  res[1] = w+85;
  a = w;
  for (j=0; j<62; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f(arg, res, iw, w+88, 0);
  if (flag) return flag;
  r = w+62;
  for (j=0; j<26; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[2];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f")==0) {
    mex_f(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f")==0) {
    return main_f(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
