/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) function_G_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[35] = {31, 1, 0, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static const casadi_int casadi_s2[15] = {14, 1, 0, 11, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., -1., 0., 0., 0., 1.};
static const casadi_real casadi_c3[3] = {1., 0., 0.};

/* f:(i0[14],i1[14],i2[31])->(o0[14x1,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+14, w2, w3, w4, *w5=w+20, *w6=w+23, *w7=w+26, *w8=w+29, *w9=w+32, *w10=w+41, w11, w12, w13, *w14=w+53, *w15=w+56, *w16=w+59, *w17=w+68, *w18=w+77, *w19=w+86, *w20=w+95, *w21=w+104, *w22=w+113, *w23=w+122, w24, w25, w26, *w27=w+134, *w28=w+143, w29, w30, *w31=w+154, *w32=w+163, *w33=w+172, *w34=w+181, *w35=w+184, *w36=w+193, *w37=w+202, *w38=w+205, *w39=w+214, w40, w41, *w42=w+225, *w43=w+234, w44, *w45=w+244, *w46=w+253;
  /* #0: @0 = zeros(14x1,11nz) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #3: @3 = input[2][3] */
  w3 = arg[2] ? arg[2][3] : 0;
  /* #4: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #5: (@1[2] += @4) */
  for (rr=w1+2, ss=(&w4); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #6: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #7: @2 = (@2*@3) */
  w2 *= w3;
  /* #8: (@5[2] += @2) */
  for (rr=w5+2, ss=(&w2); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #9: @6 = (@1+@5) */
  for (i=0, rr=w6, cr=w1, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #10: @7 = zeros(3x1) */
  casadi_clear(w7, 3);
  /* #11: @2 = input[2][1] */
  w2 = arg[2] ? arg[2][1] : 0;
  /* #12: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #13: (@7[2] += @4) */
  for (rr=w7+2, ss=(&w4); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #14: @6 = (@6+@7) */
  for (i=0, rr=w6, cs=w7; i<3; ++i) (*rr++) += (*cs++);
  /* #15: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #16: @2 = (@2*@3) */
  w2 *= w3;
  /* #17: (@8[2] += @2) */
  for (rr=w8+2, ss=(&w2); rr!=w8+3; rr+=1) *rr += *ss++;
  /* #18: @6 = (@6+@8) */
  for (i=0, rr=w6, cs=w8; i<3; ++i) (*rr++) += (*cs++);
  /* #19: {NULL, NULL, @2} = vertsplit(@6) */
  w2 = w6[2];
  /* #20: @4 = input[2][0] */
  w4 = arg[2] ? arg[2][0] : 0;
  /* #21: @4 = (@4*@3) */
  w4 *= w3;
  /* #22: @2 = (@2+@4) */
  w2 += w4;
  /* #23: (@0[0] = @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #24: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #25: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #26: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #27: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #28: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #29: @11 = cos(@3) */
  w11 = cos( w3 );
  /* #30: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #31: @12 = (-@12) */
  w12 = (- w12 );
  /* #32: @13 = 0 */
  w13 = 0.;
  /* #33: @6 = horzcat(@11, @12, @13) */
  rr=w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #34: @6 = @6' */
  /* #35: @11 = sin(@3) */
  w11 = sin( w3 );
  /* #36: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #37: @12 = 0 */
  w12 = 0.;
  /* #38: @14 = horzcat(@11, @3, @12) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w3;
  *rr++ = w12;
  /* #39: @14 = @14' */
  /* #40: @15 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w15);
  /* #41: @15 = @15' */
  /* #42: @16 = horzcat(@6, @14, @15) */
  rr=w16;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #43: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #44: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #45: @3 = cos(@11) */
  w3 = cos( w11 );
  /* #46: @12 = 0 */
  w12 = 0.;
  /* #47: @13 = sin(@11) */
  w13 = sin( w11 );
  /* #48: @6 = horzcat(@3, @12, @13) */
  rr=w6;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w13;
  /* #49: @6 = @6' */
  /* #50: @14 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w14);
  /* #51: @14 = @14' */
  /* #52: @3 = sin(@11) */
  w3 = sin( w11 );
  /* #53: @3 = (-@3) */
  w3 = (- w3 );
  /* #54: @12 = 0 */
  w12 = 0.;
  /* #55: @13 = cos(@11) */
  w13 = cos( w11 );
  /* #56: @15 = horzcat(@3, @12, @13) */
  rr=w15;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w13;
  /* #57: @15 = @15' */
  /* #58: @18 = horzcat(@6, @14, @15) */
  rr=w18;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #59: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #60: @10 = mac(@17,@19,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: @17 = @10' */
  for (i=0, rr=w17, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #62: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #63: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #64: @20 = zeros(3x3) */
  casadi_clear(w20, 9);
  /* #65: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #66: @3 = 0.5 */
  w3 = 5.0000000000000000e-001;
  /* #67: @6 = (@3*@1) */
  for (i=0, rr=w6, cs=w1; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #68: @14 = input[2][9] */
  casadi_copy(arg[2] ? arg[2]+19 : 0, 3, w14);
  /* #69: @14 = @14' */
  /* #70: @21 = mac(@6,@14,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w14+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #71: @22 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w22);
  /* #72: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #73: @20 = mac(@21,@23,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #74: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #75: @6 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w6);
  /* #76: @6 = @6' */
  /* #77: @3 = 0 */
  w3 = 0.;
  /* #78: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #79: @13 = cos(@12) */
  w13 = cos( w12 );
  /* #80: @24 = (-@12) */
  w24 = (- w12 );
  /* #81: @25 = sin(@24) */
  w25 = sin( w24 );
  /* #82: @25 = (-@25) */
  w25 = (- w25 );
  /* #83: @14 = horzcat(@3, @13, @25) */
  rr=w14;
  *rr++ = w3;
  *rr++ = w13;
  *rr++ = w25;
  /* #84: @14 = @14' */
  /* #85: @3 = 0 */
  w3 = 0.;
  /* #86: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #87: @13 = cos(@12) */
  w13 = cos( w12 );
  /* #88: @15 = horzcat(@3, @24, @13) */
  rr=w15;
  *rr++ = w3;
  *rr++ = w24;
  *rr++ = w13;
  /* #89: @15 = @15' */
  /* #90: @23 = horzcat(@6, @14, @15) */
  rr=w23;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #91: @22 = @23' */
  for (i=0, rr=w22, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #92: @3 = input[0][13] */
  w3 = arg[0] ? arg[0][13] : 0;
  /* #93: @24 = cos(@3) */
  w24 = cos( w3 );
  /* #94: @13 = 0 */
  w13 = 0.;
  /* #95: @25 = (-@3) */
  w25 = (- w3 );
  /* #96: @26 = sin(@25) */
  w26 = sin( w25 );
  /* #97: @6 = horzcat(@24, @13, @26) */
  rr=w6;
  *rr++ = w24;
  *rr++ = w13;
  *rr++ = w26;
  /* #98: @6 = @6' */
  /* #99: @14 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w14);
  /* #100: @14 = @14' */
  /* #101: @25 = sin(@25) */
  w25 = sin( w25 );
  /* #102: @25 = (-@25) */
  w25 = (- w25 );
  /* #103: @24 = 0 */
  w24 = 0.;
  /* #104: @13 = cos(@3) */
  w13 = cos( w3 );
  /* #105: @15 = horzcat(@25, @24, @13) */
  rr=w15;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w13;
  /* #106: @15 = @15' */
  /* #107: @27 = horzcat(@6, @14, @15) */
  rr=w27;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #108: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #109: @21 = mac(@22,@28,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #110: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #111: @18 = mac(@20,@22,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #112: @22 = zeros(3x3) */
  casadi_clear(w22, 9);
  /* #113: @25 = input[0][11] */
  w25 = arg[0] ? arg[0][11] : 0;
  /* #114: @24 = cos(@25) */
  w24 = cos( w25 );
  /* #115: @13 = sin(@25) */
  w13 = sin( w25 );
  /* #116: @13 = (-@13) */
  w13 = (- w13 );
  /* #117: @26 = 0 */
  w26 = 0.;
  /* #118: @6 = horzcat(@24, @13, @26) */
  rr=w6;
  *rr++ = w24;
  *rr++ = w13;
  *rr++ = w26;
  /* #119: @6 = @6' */
  /* #120: @24 = sin(@25) */
  w24 = sin( w25 );
  /* #121: @13 = cos(@25) */
  w13 = cos( w25 );
  /* #122: @26 = 0 */
  w26 = 0.;
  /* #123: @14 = horzcat(@24, @13, @26) */
  rr=w14;
  *rr++ = w24;
  *rr++ = w13;
  *rr++ = w26;
  /* #124: @14 = @14' */
  /* #125: @15 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w15);
  /* #126: @15 = @15' */
  /* #127: @21 = horzcat(@6, @14, @15) */
  rr=w21;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #128: @28 = @21' */
  for (i=0, rr=w28, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #129: @6 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w6);
  /* #130: @6 = @6' */
  /* #131: @24 = 0 */
  w24 = 0.;
  /* #132: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #133: @26 = cos(@13) */
  w26 = cos( w13 );
  /* #134: @29 = (-@13) */
  w29 = (- w13 );
  /* #135: @30 = sin(@29) */
  w30 = sin( w29 );
  /* #136: @30 = (-@30) */
  w30 = (- w30 );
  /* #137: @14 = horzcat(@24, @26, @30) */
  rr=w14;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w30;
  /* #138: @14 = @14' */
  /* #139: @24 = 0 */
  w24 = 0.;
  /* #140: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #141: @26 = cos(@13) */
  w26 = cos( w13 );
  /* #142: @15 = horzcat(@24, @29, @26) */
  rr=w15;
  *rr++ = w24;
  *rr++ = w29;
  *rr++ = w26;
  /* #143: @15 = @15' */
  /* #144: @31 = horzcat(@6, @14, @15) */
  rr=w31;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #145: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #146: @22 = mac(@28,@32,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #147: @28 = @22' */
  for (i=0, rr=w28, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #148: @19 = mac(@18,@28,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #149: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #150: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #151: @32 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w32);
  /* #152: @14 = input[2][7] */
  casadi_copy(arg[2] ? arg[2]+13 : 0, 3, w14);
  /* #153: @6 = mac(@32,@14,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #154: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #155: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #156: @33 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w33);
  /* #157: @32 = mac(@22,@33,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #158: @34 = input[2][8] */
  casadi_copy(arg[2] ? arg[2]+16 : 0, 3, w34);
  /* #159: @15 = mac(@32,@34,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #160: @6 = (@6+@15) */
  for (i=0, rr=w6, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #161: @6 = @6' */
  /* #162: @28 = mac(@1,@6,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w6+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #163: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #164: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #165: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #166: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #167: @24 = 0.5 */
  w24 = 5.0000000000000000e-001;
  /* #168: @6 = (@24*@5) */
  for (i=0, rr=w6, cs=w5; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #169: @15 = input[2][6] */
  casadi_copy(arg[2] ? arg[2]+10 : 0, 3, w15);
  /* #170: @15 = @15' */
  /* #171: @35 = mac(@6,@15,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #172: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #173: @6 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w6);
  /* #174: @6 = @6' */
  /* #175: @24 = 0 */
  w24 = 0.;
  /* #176: @29 = input[0][8] */
  w29 = arg[0] ? arg[0][8] : 0;
  /* #177: @26 = cos(@29) */
  w26 = cos( w29 );
  /* #178: @30 = sin(@29) */
  w30 = sin( w29 );
  /* #179: @30 = (-@30) */
  w30 = (- w30 );
  /* #180: @15 = horzcat(@24, @26, @30) */
  rr=w15;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w30;
  /* #181: @15 = @15' */
  /* #182: @24 = 0 */
  w24 = 0.;
  /* #183: @26 = sin(@29) */
  w26 = sin( w29 );
  /* #184: @30 = cos(@29) */
  w30 = cos( w29 );
  /* #185: @37 = horzcat(@24, @26, @30) */
  rr=w37;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w30;
  /* #186: @37 = @37' */
  /* #187: @38 = horzcat(@6, @15, @37) */
  rr=w38;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  /* #188: @39 = @38' */
  for (i=0, rr=w39, cs=w38; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #189: @24 = input[0][9] */
  w24 = arg[0] ? arg[0][9] : 0;
  /* #190: @26 = cos(@24) */
  w26 = cos( w24 );
  /* #191: @30 = 0 */
  w30 = 0.;
  /* #192: @40 = (-@24) */
  w40 = (- w24 );
  /* #193: @41 = sin(@40) */
  w41 = sin( w40 );
  /* #194: @6 = horzcat(@26, @30, @41) */
  rr=w6;
  *rr++ = w26;
  *rr++ = w30;
  *rr++ = w41;
  /* #195: @6 = @6' */
  /* #196: @15 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w15);
  /* #197: @15 = @15' */
  /* #198: @40 = sin(@40) */
  w40 = sin( w40 );
  /* #199: @40 = (-@40) */
  w40 = (- w40 );
  /* #200: @26 = 0 */
  w26 = 0.;
  /* #201: @30 = cos(@24) */
  w30 = cos( w24 );
  /* #202: @37 = horzcat(@40, @26, @30) */
  rr=w37;
  *rr++ = w40;
  *rr++ = w26;
  *rr++ = w30;
  /* #203: @37 = @37' */
  /* #204: @42 = horzcat(@6, @15, @37) */
  rr=w42;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  /* #205: @43 = @42' */
  for (i=0, rr=w43, cs=w42; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #206: @36 = mac(@39,@43,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #207: @39 = @36' */
  for (i=0, rr=w39, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #208: @32 = mac(@35,@39,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w35+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #209: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #210: @40 = input[0][7] */
  w40 = arg[0] ? arg[0][7] : 0;
  /* #211: @26 = cos(@40) */
  w26 = cos( w40 );
  /* #212: @30 = (-@40) */
  w30 = (- w40 );
  /* #213: @41 = sin(@30) */
  w41 = sin( w30 );
  /* #214: @41 = (-@41) */
  w41 = (- w41 );
  /* #215: @44 = 0 */
  w44 = 0.;
  /* #216: @6 = horzcat(@26, @41, @44) */
  rr=w6;
  *rr++ = w26;
  *rr++ = w41;
  *rr++ = w44;
  /* #217: @6 = @6' */
  /* #218: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #219: @26 = cos(@40) */
  w26 = cos( w40 );
  /* #220: @41 = 0 */
  w41 = 0.;
  /* #221: @15 = horzcat(@30, @26, @41) */
  rr=w15;
  *rr++ = w30;
  *rr++ = w26;
  *rr++ = w41;
  /* #222: @15 = @15' */
  /* #223: @37 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w37);
  /* #224: @37 = @37' */
  /* #225: @36 = horzcat(@6, @15, @37) */
  rr=w36;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  /* #226: @43 = @36' */
  for (i=0, rr=w43, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #227: @6 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w6);
  /* #228: @6 = @6' */
  /* #229: @30 = 0 */
  w30 = 0.;
  /* #230: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #231: @41 = cos(@26) */
  w41 = cos( w26 );
  /* #232: @44 = sin(@26) */
  w44 = sin( w26 );
  /* #233: @44 = (-@44) */
  w44 = (- w44 );
  /* #234: @15 = horzcat(@30, @41, @44) */
  rr=w15;
  *rr++ = w30;
  *rr++ = w41;
  *rr++ = w44;
  /* #235: @15 = @15' */
  /* #236: @30 = 0 */
  w30 = 0.;
  /* #237: @41 = sin(@26) */
  w41 = sin( w26 );
  /* #238: @44 = cos(@26) */
  w44 = cos( w26 );
  /* #239: @37 = horzcat(@30, @41, @44) */
  rr=w37;
  *rr++ = w30;
  *rr++ = w41;
  *rr++ = w44;
  /* #240: @37 = @37' */
  /* #241: @45 = horzcat(@6, @15, @37) */
  rr=w45;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  /* #242: @46 = @45' */
  for (i=0, rr=w46, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @39 = mac(@43,@46,@39) */
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w43+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #244: @43 = @39' */
  for (i=0, rr=w43, cs=w39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #245: @28 = mac(@32,@43,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w43+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #246: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #247: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #248: @6 = input[2][4] */
  casadi_copy(arg[2] ? arg[2]+4 : 0, 3, w6);
  /* #249: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #250: @37 = input[2][5] */
  casadi_copy(arg[2] ? arg[2]+7 : 0, 3, w37);
  /* #251: @15 = mac(@39,@37,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #252: @15 = (@6+@15) */
  for (i=0, rr=w15, cr=w6, cs=w15; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #253: @15 = @15' */
  /* #254: @28 = mac(@5,@15,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #255: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #256: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #257: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #258: @43 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w43);
  /* #259: @15 = mac(@43,@14,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w43+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #260: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #261: @43 = zeros(3x3) */
  casadi_clear(w43, 9);
  /* #262: @46 = 
  [[1, 0, 0], 
   [0, -1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w46);
  /* #263: @43 = mac(@22,@46,@43) */
  for (i=0, rr=w43; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #264: @14 = mac(@43,@34,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w43+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #265: @30 = 2 */
  w30 = 2.;
  /* #266: @14 = (@14/@30) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w30;
  /* #267: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #268: @15 = @15' */
  /* #269: @28 = mac(@7,@15,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #270: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #271: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #272: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #273: @15 = mac(@39,@37,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #274: @30 = 2 */
  w30 = 2.;
  /* #275: @15 = (@15/@30) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) /= w30;
  /* #276: @6 = (@6+@15) */
  for (i=0, rr=w6, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #277: @6 = @6' */
  /* #278: @28 = mac(@8,@6,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w6+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #279: @19 = (@19+@28) */
  for (i=0, rr=w19, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #280: @9 = mac(@17,@19,@9) */
  for (i=0, rr=w9; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #281: @17 = @9' */
  for (i=0, rr=w17, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #282: {NULL, @6, @15} = horzsplit(@17) */
  casadi_copy(w17+3, 3, w6);
  casadi_copy(w17+6, 3, w15);
  /* #283: @15 = @15' */
  /* #284: {NULL, @30, @41} = horzsplit(@15) */
  w30 = w15[1];
  w41 = w15[2];
  /* #285: @4 = (@4*@30) */
  w4 *= w30;
  /* #286: @30 = sin(@2) */
  w30 = sin( w2 );
  /* #287: @30 = (@30*@41) */
  w30 *= w41;
  /* #288: @4 = (@4-@30) */
  w4 -= w30;
  /* #289: @30 = cos(@2) */
  w30 = cos( w2 );
  /* #290: @6 = @6' */
  /* #291: {NULL, @41, @44} = horzsplit(@6) */
  w41 = w6[1];
  w44 = w6[2];
  /* #292: @30 = (@30*@44) */
  w30 *= w44;
  /* #293: @4 = (@4-@30) */
  w4 -= w30;
  /* #294: @30 = sin(@2) */
  w30 = sin( w2 );
  /* #295: @30 = (@30*@41) */
  w30 *= w41;
  /* #296: @4 = (@4-@30) */
  w4 -= w30;
  /* #297: (@0[1] = @4) */
  for (rr=w0+1, ss=(&w4); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #298: @4 = cos(@11) */
  w4 = cos( w11 );
  /* #299: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #300: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #301: @6 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w6);
  /* #302: @6 = @6' */
  /* #303: @30 = 0 */
  w30 = 0.;
  /* #304: @41 = cos(@2) */
  w41 = cos( w2 );
  /* #305: @44 = sin(@2) */
  w44 = sin( w2 );
  /* #306: @44 = (-@44) */
  w44 = (- w44 );
  /* #307: @15 = horzcat(@30, @41, @44) */
  rr=w15;
  *rr++ = w30;
  *rr++ = w41;
  *rr++ = w44;
  /* #308: @15 = @15' */
  /* #309: @30 = 0 */
  w30 = 0.;
  /* #310: @41 = sin(@2) */
  w41 = sin( w2 );
  /* #311: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #312: @14 = horzcat(@30, @41, @2) */
  rr=w14;
  *rr++ = w30;
  *rr++ = w41;
  *rr++ = w2;
  /* #313: @14 = @14' */
  /* #314: @28 = horzcat(@6, @15, @14) */
  rr=w28;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #315: @9 = mac(@19,@28,@9) */
  for (i=0, rr=w9; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #316: @17 = mac(@16,@9,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #317: @16 = @17' */
  for (i=0, rr=w16, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #318: {@6, NULL, @15} = horzsplit(@16) */
  casadi_copy(w16, 3, w6);
  casadi_copy(w16+6, 3, w15);
  /* #319: @15 = @15' */
  /* #320: {@30, NULL, @41} = horzsplit(@15) */
  w30 = w15[0];
  w41 = w15[2];
  /* #321: @4 = (@4*@30) */
  w4 *= w30;
  /* #322: @4 = (-@4) */
  w4 = (- w4 );
  /* #323: @30 = sin(@11) */
  w30 = sin( w11 );
  /* #324: @30 = (@30*@41) */
  w30 *= w41;
  /* #325: @4 = (@4-@30) */
  w4 -= w30;
  /* #326: @30 = cos(@11) */
  w30 = cos( w11 );
  /* #327: @6 = @6' */
  /* #328: {@41, NULL, @2} = horzsplit(@6) */
  w41 = w6[0];
  w2 = w6[2];
  /* #329: @30 = (@30*@2) */
  w30 *= w2;
  /* #330: @4 = (@4+@30) */
  w4 += w30;
  /* #331: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #332: @11 = (@11*@41) */
  w11 *= w41;
  /* #333: @4 = (@4-@11) */
  w4 -= w11;
  /* #334: (@0[2] = @4) */
  for (rr=w0+2, ss=(&w4); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #335: @4 = cos(@26) */
  w4 = cos( w26 );
  /* #336: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #337: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #338: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #339: @19 = @28' */
  for (i=0, rr=w19, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #340: @9 = mac(@10,@19,@9) */
  for (i=0, rr=w9; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #341: @10 = @9' */
  for (i=0, rr=w10, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #342: @17 = mac(@10,@32,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #343: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #344: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #345: @32 = @9' */
  for (i=0, rr=w32, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #346: @6 = mac(@32,@5,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #347: @5 = @37' */
  casadi_copy(w37, 3, w5);
  /* #348: @10 = mac(@6,@5,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w5+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #349: @17 = (@17+@10) */
  for (i=0, rr=w17, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #350: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #351: @11 = 0.5 */
  w11 = 5.0000000000000000e-001;
  /* #352: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #353: @32 = @9' */
  for (i=0, rr=w32, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #354: @6 = mac(@32,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #355: @6 = (@11*@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #356: @37 = @37' */
  /* #357: @10 = mac(@6,@37,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w37+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #358: @17 = (@17+@10) */
  for (i=0, rr=w17, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #359: @16 = mac(@36,@17,@16) */
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #360: @36 = @16' */
  for (i=0, rr=w36, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #361: {NULL, @6, @37} = horzsplit(@36) */
  casadi_copy(w36+3, 3, w6);
  casadi_copy(w36+6, 3, w37);
  /* #362: @37 = @37' */
  /* #363: {NULL, @11, @41} = horzsplit(@37) */
  w11 = w37[1];
  w41 = w37[2];
  /* #364: @4 = (@4*@11) */
  w4 *= w11;
  /* #365: @11 = sin(@26) */
  w11 = sin( w26 );
  /* #366: @11 = (@11*@41) */
  w11 *= w41;
  /* #367: @4 = (@4-@11) */
  w4 -= w11;
  /* #368: @11 = cos(@26) */
  w11 = cos( w26 );
  /* #369: @6 = @6' */
  /* #370: {NULL, @41, @30} = horzsplit(@6) */
  w41 = w6[1];
  w30 = w6[2];
  /* #371: @11 = (@11*@30) */
  w11 *= w30;
  /* #372: @4 = (@4-@11) */
  w4 -= w11;
  /* #373: @26 = sin(@26) */
  w26 = sin( w26 );
  /* #374: @26 = (@26*@41) */
  w26 *= w41;
  /* #375: @4 = (@4-@26) */
  w4 -= w26;
  /* #376: (@0[3] = @4) */
  for (rr=w0+3, ss=(&w4); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #377: @4 = cos(@40) */
  w4 = cos( w40 );
  /* #378: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #379: @36 = mac(@17,@45,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #380: @17 = @36' */
  for (i=0, rr=w17, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #381: {@6, @37, NULL} = horzsplit(@17) */
  casadi_copy(w17, 3, w6);
  casadi_copy(w17+3, 3, w37);
  /* #382: @37 = @37' */
  /* #383: {@26, @41, NULL} = horzsplit(@37) */
  w26 = w37[0];
  w41 = w37[1];
  /* #384: @4 = (@4*@26) */
  w4 *= w26;
  /* #385: @26 = cos(@40) */
  w26 = cos( w40 );
  /* #386: @6 = @6' */
  /* #387: {@11, @30, NULL} = horzsplit(@6) */
  w11 = w6[0];
  w30 = w6[1];
  /* #388: @26 = (@26*@30) */
  w26 *= w30;
  /* #389: @4 = (@4-@26) */
  w4 -= w26;
  /* #390: @4 = (-@4) */
  w4 = (- w4 );
  /* #391: @26 = sin(@40) */
  w26 = sin( w40 );
  /* #392: @26 = (@26*@41) */
  w26 *= w41;
  /* #393: @4 = (@4-@26) */
  w4 -= w26;
  /* #394: @40 = sin(@40) */
  w40 = sin( w40 );
  /* #395: @40 = (@40*@11) */
  w40 *= w11;
  /* #396: @4 = (@4-@40) */
  w4 -= w40;
  /* #397: (@0[4] = @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #398: @4 = cos(@29) */
  w4 = cos( w29 );
  /* #399: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #400: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #401: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #402: @45 = mac(@9,@39,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #403: @39 = @45' */
  for (i=0, rr=w39, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #404: @36 = mac(@39,@35,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w39+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #405: @17 = mac(@36,@42,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #406: @42 = @17' */
  for (i=0, rr=w42, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #407: {NULL, @6, @37} = horzsplit(@42) */
  casadi_copy(w42+3, 3, w6);
  casadi_copy(w42+6, 3, w37);
  /* #408: @37 = @37' */
  /* #409: {NULL, @40, @11} = horzsplit(@37) */
  w40 = w37[1];
  w11 = w37[2];
  /* #410: @4 = (@4*@40) */
  w4 *= w40;
  /* #411: @40 = sin(@29) */
  w40 = sin( w29 );
  /* #412: @40 = (@40*@11) */
  w40 *= w11;
  /* #413: @4 = (@4-@40) */
  w4 -= w40;
  /* #414: @40 = cos(@29) */
  w40 = cos( w29 );
  /* #415: @6 = @6' */
  /* #416: {NULL, @11, @26} = horzsplit(@6) */
  w11 = w6[1];
  w26 = w6[2];
  /* #417: @40 = (@40*@26) */
  w40 *= w26;
  /* #418: @4 = (@4-@40) */
  w4 -= w40;
  /* #419: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #420: @29 = (@29*@11) */
  w29 *= w11;
  /* #421: @4 = (@4-@29) */
  w4 -= w29;
  /* #422: (@0[5] = @4) */
  for (rr=w0+5, ss=(&w4); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #423: @4 = cos(@24) */
  w4 = cos( w24 );
  /* #424: @42 = zeros(3x3) */
  casadi_clear(w42, 9);
  /* #425: @42 = mac(@38,@36,@42) */
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w38+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #426: @38 = @42' */
  for (i=0, rr=w38, cs=w42; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #427: {@6, NULL, @37} = horzsplit(@38) */
  casadi_copy(w38, 3, w6);
  casadi_copy(w38+6, 3, w37);
  /* #428: @6 = @6' */
  /* #429: {@29, NULL, @11} = horzsplit(@6) */
  w29 = w6[0];
  w11 = w6[2];
  /* #430: @4 = (@4*@11) */
  w4 *= w11;
  /* #431: @11 = cos(@24) */
  w11 = cos( w24 );
  /* #432: @37 = @37' */
  /* #433: {@40, NULL, @26} = horzsplit(@37) */
  w40 = w37[0];
  w26 = w37[2];
  /* #434: @11 = (@11*@40) */
  w11 *= w40;
  /* #435: @4 = (@4-@11) */
  w4 -= w11;
  /* #436: @4 = (-@4) */
  w4 = (- w4 );
  /* #437: @11 = sin(@24) */
  w11 = sin( w24 );
  /* #438: @11 = (@11*@26) */
  w11 *= w26;
  /* #439: @4 = (@4-@11) */
  w4 -= w11;
  /* #440: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #441: @24 = (@24*@29) */
  w24 *= w29;
  /* #442: @4 = (@4-@24) */
  w4 -= w24;
  /* #443: (@0[6] = @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #444: @4 = cos(@13) */
  w4 = cos( w13 );
  /* #445: @38 = zeros(3x3) */
  casadi_clear(w38, 9);
  /* #446: @42 = zeros(3x3) */
  casadi_clear(w42, 9);
  /* #447: @36 = @9' */
  for (i=0, rr=w36, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #448: @42 = mac(@36,@18,@42) */
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w36+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #449: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #450: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #451: @37 = zeros(3x1) */
  casadi_clear(w37, 3);
  /* #452: @17 = @9' */
  for (i=0, rr=w17, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #453: @37 = mac(@17,@1,@37) */
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #454: @1 = @34' */
  casadi_copy(w34, 3, w1);
  /* #455: @18 = mac(@37,@1,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w37+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #456: @17 = @33' */
  for (i=0, rr=w17, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #457: @36 = mac(@18,@17,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #458: @42 = (@42+@36) */
  for (i=0, rr=w42, cs=w36; i<9; ++i) (*rr++) += (*cs++);
  /* #459: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #460: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #461: @24 = 0.5 */
  w24 = 5.0000000000000000e-001;
  /* #462: @37 = zeros(3x1) */
  casadi_clear(w37, 3);
  /* #463: @17 = @9' */
  for (i=0, rr=w17, cs=w9; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #464: @37 = mac(@17,@7,@37) */
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #465: @37 = (@24*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #466: @34 = @34' */
  /* #467: @18 = mac(@37,@34,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w37+j, tt=w34+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #468: @17 = @46' */
  for (i=0, rr=w17, cs=w46; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #469: @36 = mac(@18,@17,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #470: @42 = (@42+@36) */
  for (i=0, rr=w42, cs=w36; i<9; ++i) (*rr++) += (*cs++);
  /* #471: @38 = mac(@21,@42,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w42+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #472: @21 = @38' */
  for (i=0, rr=w21, cs=w38; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #473: {NULL, @37, @34} = horzsplit(@21) */
  casadi_copy(w21+3, 3, w37);
  casadi_copy(w21+6, 3, w34);
  /* #474: @34 = @34' */
  /* #475: {NULL, @24, @29} = horzsplit(@34) */
  w24 = w34[1];
  w29 = w34[2];
  /* #476: @4 = (@4*@24) */
  w4 *= w24;
  /* #477: @24 = cos(@13) */
  w24 = cos( w13 );
  /* #478: @37 = @37' */
  /* #479: {NULL, @11, @26} = horzsplit(@37) */
  w11 = w37[1];
  w26 = w37[2];
  /* #480: @24 = (@24*@26) */
  w24 *= w26;
  /* #481: @4 = (@4-@24) */
  w4 -= w24;
  /* #482: @4 = (-@4) */
  w4 = (- w4 );
  /* #483: @24 = sin(@13) */
  w24 = sin( w13 );
  /* #484: @24 = (@24*@29) */
  w24 *= w29;
  /* #485: @4 = (@4-@24) */
  w4 -= w24;
  /* #486: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #487: @13 = (@13*@11) */
  w13 *= w11;
  /* #488: @4 = (@4-@13) */
  w4 -= w13;
  /* #489: (@0[7] = @4) */
  for (rr=w0+7, ss=(&w4); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #490: @4 = cos(@25) */
  w4 = cos( w25 );
  /* #491: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #492: @21 = mac(@42,@31,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w42+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #493: @42 = @21' */
  for (i=0, rr=w42, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #494: {@37, @34, NULL} = horzsplit(@42) */
  casadi_copy(w42, 3, w37);
  casadi_copy(w42+3, 3, w34);
  /* #495: @34 = @34' */
  /* #496: {@13, @11, NULL} = horzsplit(@34) */
  w13 = w34[0];
  w11 = w34[1];
  /* #497: @4 = (@4*@13) */
  w4 *= w13;
  /* #498: @13 = sin(@25) */
  w13 = sin( w25 );
  /* #499: @13 = (@13*@11) */
  w13 *= w11;
  /* #500: @4 = (@4-@13) */
  w4 -= w13;
  /* #501: @13 = cos(@25) */
  w13 = cos( w25 );
  /* #502: @37 = @37' */
  /* #503: {@11, @24, NULL} = horzsplit(@37) */
  w11 = w37[0];
  w24 = w37[1];
  /* #504: @13 = (@13*@24) */
  w13 *= w24;
  /* #505: @4 = (@4-@13) */
  w4 -= w13;
  /* #506: @25 = sin(@25) */
  w25 = sin( w25 );
  /* #507: @25 = (@25*@11) */
  w25 *= w11;
  /* #508: @4 = (@4-@25) */
  w4 -= w25;
  /* #509: (@0[8] = @4) */
  for (rr=w0+8, ss=(&w4); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #510: @4 = cos(@12) */
  w4 = cos( w12 );
  /* #511: @42 = zeros(3x3) */
  casadi_clear(w42, 9);
  /* #512: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #513: @31 = zeros(3x3) */
  casadi_clear(w31, 9);
  /* #514: @31 = mac(@9,@22,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #515: @9 = @31' */
  for (i=0, rr=w9, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #516: @21 = mac(@9,@20,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #517: @42 = mac(@21,@27,@42) */
  for (i=0, rr=w42; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #518: @27 = @42' */
  for (i=0, rr=w27, cs=w42; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #519: {NULL, @37, @34} = horzsplit(@27) */
  casadi_copy(w27+3, 3, w37);
  casadi_copy(w27+6, 3, w34);
  /* #520: @34 = @34' */
  /* #521: {NULL, @25, @11} = horzsplit(@34) */
  w25 = w34[1];
  w11 = w34[2];
  /* #522: @4 = (@4*@25) */
  w4 *= w25;
  /* #523: @25 = cos(@12) */
  w25 = cos( w12 );
  /* #524: @37 = @37' */
  /* #525: {NULL, @13, @24} = horzsplit(@37) */
  w13 = w37[1];
  w24 = w37[2];
  /* #526: @25 = (@25*@24) */
  w25 *= w24;
  /* #527: @4 = (@4-@25) */
  w4 -= w25;
  /* #528: @4 = (-@4) */
  w4 = (- w4 );
  /* #529: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #530: @25 = (@25*@11) */
  w25 *= w11;
  /* #531: @4 = (@4-@25) */
  w4 -= w25;
  /* #532: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #533: @12 = (@12*@13) */
  w12 *= w13;
  /* #534: @4 = (@4-@12) */
  w4 -= w12;
  /* #535: (@0[9] = @4) */
  for (rr=w0+9, ss=(&w4); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #536: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #537: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #538: @27 = mac(@23,@21,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #539: @23 = @27' */
  for (i=0, rr=w23, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #540: {@37, NULL, @34} = horzsplit(@23) */
  casadi_copy(w23, 3, w37);
  casadi_copy(w23+6, 3, w34);
  /* #541: @37 = @37' */
  /* #542: {@12, NULL, @13} = horzsplit(@37) */
  w12 = w37[0];
  w13 = w37[2];
  /* #543: @4 = (@4*@13) */
  w4 *= w13;
  /* #544: @13 = cos(@3) */
  w13 = cos( w3 );
  /* #545: @34 = @34' */
  /* #546: {@25, NULL, @11} = horzsplit(@34) */
  w25 = w34[0];
  w11 = w34[2];
  /* #547: @13 = (@13*@25) */
  w13 *= w25;
  /* #548: @4 = (@4-@13) */
  w4 -= w13;
  /* #549: @4 = (-@4) */
  w4 = (- w4 );
  /* #550: @13 = sin(@3) */
  w13 = sin( w3 );
  /* #551: @13 = (@13*@11) */
  w13 *= w11;
  /* #552: @4 = (@4-@13) */
  w4 -= w13;
  /* #553: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #554: @3 = (@3*@12) */
  w3 *= w12;
  /* #555: @4 = (@4-@3) */
  w4 -= w3;
  /* #556: (@0[10] = @4) */
  for (rr=w0+10, ss=(&w4); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #557: output[0][0] = @0 */
  casadi_copy(w0, 11, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 262;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[332];
  casadi_int *iw = 0;
  const casadi_real* arg[6] = {0};
  casadi_real* res[4] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+70);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+14, casadi_s0, w+70);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+28, casadi_s1, w+70);
  --resc;
  res[0] = w+59;
  i = f(arg, res, iw, w+70, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif

casadi_int main_f(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[332];
  const casadi_real* arg[6];
  casadi_real* res[4];
  arg[0] = w+0;
  arg[1] = w+14;
  arg[2] = w+28;
  res[0] = w+59;
  a = w;
  for (j=0; j<59; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f(arg, res, iw, w+70, 0);
  if (flag) return flag;
  r = w+59;
  for (j=0; j<11; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[2];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f")==0) {
    mex_f(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f")==0) {
    return main_f(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
